# 초기 모델 학습 방법

# Step 1. 혼잡도 데이터 전처리

In [5]:
import numpy as np
import pandas as pd

station_order = [
        '오금', '경찰병원', '가락시장', '수서', '일원', '대청', '학여울', '대치', '도곡', '매봉',
        '양재', '남부터미널', '교대', '고속터미널', '잠원', '신사', '압구정', '옥수', '금호',
        '약수', '동대입구', '충무로', '을지로3가', '종로3가', '안국', '경복궁', '독립문',
        '무악재', '홍제', '녹번', '불광', '연신내', '구파발', '지축', '삼송', '원흥', '원당',
        '화정', '대곡', '백석', '마두', '정발산', '주엽', '대화'
    ]

def process_congestion_data(congestion):
    
    # 1. 컬럼명 변경
    congestion = congestion.rename(columns={'5시30분': '6시 이전'})
    
    # 2. 23시 이후 평균 컬럼 생성
    congestion['23시 이후'] = congestion[['23시00분', '23시30분', '00시00분', '00시30분']].mean(axis=1).round(2)
    
    # 3. 불필요 컬럼 제거
    congestion.drop(columns=['23시00분', '23시30분', '00시00분', '00시30분', '역번호', '연번'], inplace=True, errors='ignore')
    
    # 4. 역 순서 및 레이블 매핑
    station_label_map = {station: i for i, station in enumerate(station_order)}
    
    # 5. 정렬 및 결측치 처리
    congestion = congestion.sort_values(by=['요일구분', '상하구분']).reset_index(drop=True)
    congestion = congestion.fillna(0)
    
    # 6. 역번호 컬럼 추가
    congestion['역번호'] = congestion['출발역'].map(station_label_map)
    
    return congestion

In [7]:
congest_2024_1 = pd.read_csv('2024년 1분기 3호선 지하철혼잡도_30분단위(평일, 토요일, 공휴일 구분).csv', encoding = 'cp949')

congestion_2024_1 = process_congestion_data(congest_2024_1)
congestion_2024_1.head()

,요일구분,호선,출발역,상하구분,6시 이전,6시00분,6시30분,7시00분,7시30분,8시00분,...,19시00분,19시30분,20시00분,20시30분,21시00분,21시30분,22시00분,22시30분,23시 이후,역번호
0,일요일,3,지축,상선,9.3,5.2,5.3,6.0,6.6,10.4,...,31.9,34.5,23.9,28.2,20.4,21.7,29.0,20.4,23.20,33
1,일요일,3,구파발,상선,9.7,5.6,3.5,2.4,4.0,6.2,...,15.7,21.7,13.1,22.6,22.3,14.0,15.3,17.5,3.97,32
2,일요일,3,연신내,상선,9.9,7.1,4.2,3.9,5.9,7.4,...,22.8,22.5,19.0,22.2,26.3,20.5,18.2,17.5,7.07,31
3,일요일,3,불광,상선,8.6,7.9,4.0,5.0,6.1,7.8,...,28.9,28.3,24.8,30.1,33.7,26.6,24.4,20.6,10.33,30
4,일요일,3,녹번,상선,7.2,6.9,3.5,5.4,5.7,7.7,...,30.0,27.2,25.3,32.5,35.5,27.3,24.3,20.9,14.55,29

In [9]:
congestion_2024_1.to_csv('2024년 1분기 3호선 지하철혼잡도_30분단위(평일, 토요일, 공휴일 구분)(전처리).csv')

In [11]:
congestion_2024_2 = pd.read_csv('2024년 2분기 3호선 지하철혼잡도_30분단위(평일, 토요일, 공휴일 구분).csv', encoding = 'cp949')

congestion_2024_2 = process_congestion_data(congestion_2024_2)
congestion_2024_2.head()

,요일구분,호선,출발역,상하구분,6시 이전,6시00분,6시30분,7시00분,7시30분,8시00분,...,19시00분,19시30분,20시00분,20시30분,21시00분,21시30분,22시00분,22시30분,23시 이후,역번호
0,일요일,3,지축,상선,10.2,6.9,4.8,7.0,6.6,10.2,...,28.7,29.3,22.3,24.9,19.0,19.6,30.7,21.4,20.55,33
1,일요일,3,구파발,상선,10.5,7.6,3.8,2.8,4.0,6.0,...,14.2,19.2,12.5,19.6,20.6,12.7,15.8,17.2,3.60,32
2,일요일,3,연신내,상선,10.1,9.4,4.4,4.4,5.4,7.1,...,20.9,20.5,17.7,20.1,23.7,18.7,19.7,16.8,6.33,31
3,일요일,3,불광,상선,9.5,8.8,4.2,5.3,5.9,8.0,...,25.7,26.3,22.7,26.9,28.7,25.8,26.3,21.1,9.37,30
4,일요일,3,녹번,상선,8.8,7.6,4.0,6.0,5.6,8.1,...,26.0,25.7,23.6,30.0,30.5,25.9,27.1,21.1,13.00,29

In [13]:
congestion_2024_2.to_csv('2024년 2분기 3호선 지하철혼잡도_30분단위(평일, 토요일, 공휴일 구분)(전처리).csv')

In [15]:
congestion_2024_3 = pd.read_csv('2024년 3분기 3호선 지하철혼잡도_30분단위(평일, 토요일, 공휴일 구분).csv', encoding = 'cp949')

congestion_2024_3 = process_congestion_data(congestion_2024_3)
congestion_2024_3.head()

,요일구분,호선,출발역,상하구분,6시 이전,6시00분,6시30분,7시00분,7시30분,8시00분,...,19시00분,19시30분,20시00분,20시30분,21시00분,21시30분,22시00분,22시30분,23시 이후,역번호
0,일요일,3,지축,하선,24.2,10.9,13.6,14.5,22.0,30.2,...,19.9,17.4,11.5,15.6,8.9,10.2,13.1,6.8,3.03,33
1,일요일,3,구파발,하선,1.9,10.5,6.6,10.6,12.3,19.2,...,10.7,12.9,9.5,10.5,10.6,9.7,8.1,5.6,2.87,32
2,일요일,3,연신내,하선,5.3,11.3,9.2,9.5,14.4,19.6,...,13.4,10.3,11.8,7.6,10.2,9.1,6.9,6.4,3.80,31
3,일요일,3,불광,하선,8.2,13.4,10.6,11.5,18.2,21.5,...,16.0,12.1,12.8,8.5,11.6,10.3,8.2,7.3,4.20,30
4,일요일,3,녹번,하선,10.2,14.7,11.7,13.3,20.5,24.3,...,15.8,12.0,12.9,8.5,11.5,9.8,8.3,6.8,3.90,29

In [17]:
congestion_2024_3.to_csv('2024년 3분기 3호선 지하철혼잡도_30분단위(평일, 토요일, 공휴일 구분)(전처리).csv')

In [19]:
congestion = pd.read_excel('2024년 4분기 3호선 지하철혼잡도_30분단위(평일, 토요일, 공휴일 구분).xlsx')

congestion_2024_4 = process_congestion_data(congestion)
congestion_2024_4.head()

,요일구분,호선,출발역,상하구분,6시 이전,6시00분,6시30분,7시00분,7시30분,8시00분,...,19시00분,19시30분,20시00분,20시30분,21시00분,21시30분,22시00분,22시30분,23시 이후,역번호
0,일요일,3,지축,상선,10.120558,7.146256,7.082805,7.651227,9.152919,11.770305,...,32.143613,34.168782,23.374048,28.066836,19.630393,20.801607,29.933376,19.812817,14.04,33
1,일요일,3,구파발,상선,10.136421,7.645939,4.457487,3.020305,5.482234,7.268401,...,16.072335,21.579949,12.779188,22.660216,20.828046,13.416878,15.783629,16.608503,3.62,32
2,일요일,3,연신내,상선,10.406091,8.700825,5.203046,4.673223,7.366751,8.239213,...,23.629442,22.671320,19.026015,22.763325,24.591529,19.838198,17.354061,16.802824,6.94,31
3,일요일,3,불광,상선,9.708122,8.973139,5.149112,5.516339,7.560279,8.777496,...,29.386104,28.207487,24.171954,29.314721,31.499841,25.924016,23.029822,20.695854,10.56,30
4,일요일,3,녹번,상선,8.819797,7.862733,4.854061,5.837563,6.786168,8.651650,...,30.761421,27.557107,25.336294,30.940673,32.796637,26.329315,23.893560,20.550444,8.88,29

In [21]:
congestion_2024_4.to_csv('2024년 4분기 3호선 지하철혼잡도_30분단위(평일, 토요일, 공휴일 구분)(전처리).csv')

In [23]:
# 혼잡도 데이터 합치기
def average_congestion_sum_then_divide(congest_2024_1, congest_2024_2, congest_2024_3, congest_2024_4):
    non_time_cols = ['요일구분', '호선', '출발역', '상하구분', '역번호']
    time_cols = [col for col in congest_2024_1.columns if col not in non_time_cols]

    # 외부 조인으로 병합
    merged_df = pd.merge(congest_2024_1, congest_2024_2, on=non_time_cols, how='outer', suffixes=('_1', '_2'))
    merged_df = pd.merge(merged_df, congest_2024_3, on=non_time_cols, how='outer')
    merged_df = pd.merge(merged_df, congest_2024_4, on=non_time_cols, how='outer', suffixes=('_3', '_4'))
    
    # 결측치 처리
    merged_df.fillna(0, inplace=True)

    # 컬럼명 정규화
    for col in time_cols:
        merged_df.rename(columns={col: f'{col}_3'}, inplace=True)
        merged_df.rename(columns={col: f'{col}_4'}, inplace=True)

    # 평균 계산
    result_df = merged_df[non_time_cols].copy()
    for col in time_cols:
        cols_to_sum = [f'{col}_1', f'{col}_2', f'{col}_3', f'{col}_4']
        result_df[col] = merged_df[cols_to_sum].sum(axis=1) / 4

    return result_df

mean_df = average_congestion_sum_then_divide(congestion_2024_1, congestion_2024_2, congestion_2024_3, congestion_2024_4)
mean_df.head()

,요일구분,호선,출발역,상하구분,역번호,6시 이전,6시00분,6시30분,7시00분,7시30분,...,18시30분,19시00분,19시30분,20시00분,20시30분,21시00분,21시30분,22시00분,22시30분,23시 이후
0,일요일,3,가락시장,상선,2,3.878754,5.192782,3.019956,2.973477,3.292418,...,5.821732,4.393845,4.802720,5.291656,5.578141,4.924215,4.772256,4.136160,2.451195,1.7900
1,일요일,3,가락시장,하선,2,0.000000,2.988832,1.765411,1.608685,1.581488,...,7.126221,5.632075,6.000523,5.339213,7.881546,7.018369,5.706282,6.773112,7.290609,3.0725
2,일요일,3,경복궁,상선,25,5.265958,4.550835,3.674143,4.789848,5.230108,...,32.364166,26.247018,25.209074,23.850857,32.008344,29.229188,24.384851,25.168742,19.512730,9.6525
3,일요일,3,경복궁,하선,25,11.653151,13.434248,12.964530,12.672494,18.792132,...,24.835406,23.276872,17.771478,19.290102,15.335216,15.320907,15.309518,14.260081,8.377966,4.9375
4,일요일,3,경찰병원,상선,1,2.782725,3.431710,1.995971,1.948979,2.710533,...,3.031091,2.168940,2.845082,3.112701,3.570654,3.109177,2.623802,2.255822,1.362553,0.8125

In [25]:
mean_df.to_csv('2024년 3호선 지하철혼잡도_30분단위(평일, 토요일, 공휴일 구분)(전처리).csv')

# Step 2. 승하차 데이터 전처리

In [27]:
import numpy as np
import pandas as pd
from datetime import datetime
import holidays
import re

station_order = [
    '오금', '경찰병원', '가락시장', '수서', '일원', '대청', '학여울', '대치', '도곡', '매봉',
    '양재', '남부터미널', '교대', '고속터미널', '잠원', '신사', '압구정', '옥수', '금호',
    '약수', '동대입구', '충무로', '을지로3가', '종로3가', '안국', '경복궁', '독립문',
    '무악재', '홍제', '녹번', '불광', '연신내', '구파발', '지축', '삼송', '원흥', '원당',
    '화정', '대곡', '백석', '마두', '정발산', '주엽', '대화'
]

kr_holidays = holidays.KR(years=[2024])

def get_day_type(date):
    if date in kr_holidays or date.weekday() == 6:
        return '공휴일'
    elif date.weekday() == 5:
        return '토요일'
    else:
        return '평일'

In [29]:
def process_subway_data(file_path, station_order):
    
    # 1. 데이터 로드 및 필터링
    df = pd.read_csv(file_path, encoding='cp949')
    df_3 = df[df['호선'] == '3호선'].copy()
    
    # 2. 역명 정제
    df_3['역명'] = df_3['역명'].str.replace(r'\(.*\)', '', regex=True).str.strip()
    
    # 3. 역 순서 라벨링
    station_label_map = {station: i for i, station in enumerate(station_order)}
    df_3['label'] = df_3['역명'].map(station_label_map)
    
    # 4. 정렬
    df_3 = df_3.sort_values(by=['label', '날짜', '구분']).reset_index(drop=True)
    
    # 5. 날짜 처리
    df_3['날짜'] = pd.to_datetime(df_3['날짜'])
    df_3['요일구분'] = df_3['날짜'].apply(get_day_type)
    
    # 6. 불필요 컬럼 제거
    if '역번호' in df_3.columns:
        df_3.drop(columns='역번호', inplace=True)
        
    return df_3

In [33]:
path = '서울교통공사_역별 시간대별 승하차인원(24.1~24.12).csv'

df2024 = process_subway_data(path, station_order)
df2024.head()

,연번,날짜,호선,역명,구분,06시 이전,06시-07시,07시-08시,08시-09시,09시-10시,...,17시-18시,18시-19시,19시-20시,20시-21시,21시-22시,22시-23시,23시-24시,24시 이후,label,요일구분
0,185,2024-01-01,3호선,오금,승차,77,77,82,113,132,...,115,107,80,87,32,32,3,0,0,공휴일
1,186,2024-01-01,3호선,오금,하차,1,57,44,53,66,...,172,162,147,143,122,172,92,23,0,공휴일
2,729,2024-01-02,3호선,오금,승차,189,351,1261,1397,605,...,387,498,185,125,104,61,26,1,0,평일
3,730,2024-01-02,3호선,오금,하차,2,106,257,555,226,...,498,1041,719,400,334,358,160,73,0,평일
4,1273,2024-01-03,3호선,오금,승차,184,353,1288,1451,603,...,428,552,198,124,100,90,91,2,0,평일

In [35]:
df2024.to_excel('2024년 1월 ~ 12월 역별 시간대별 이용인원(전처리).xlsx', index=False)

# Step 3. 승차량 - 하차량의 데이터프레임 생성

In [37]:
def analyze_passenger_flow(passenger_df):
    
    # 1. 분기 정보 생성
    passenger_df['분기'] = passenger_df['날짜'].dt.to_period('Q')
    
    # 2. 불필요 컬럼 제거
    if '합 계' in passenger_df.columns:
        passenger_df = passenger_df.drop(columns=['합 계'])
    
    # 3. 시간대 컬럼 추출
    time_columns = [col for col in passenger_df.columns 
                   if col not in ['날짜', '호선', '역명', '구분', '요일구분', '분기']]
    
    # 4. 그룹화 및 집계
    grouped = passenger_df.groupby(['분기', '역명', '구분', '요일구분'])[time_columns].sum().reset_index()
    
    # 5. 승차/하차 데이터 분리
    boarding_df = grouped[grouped['구분'] == '승차'].drop('구분', axis=1)
    alighting_df = grouped[grouped['구분'] == '하차'].drop('구분', axis=1)
    
    # 6. 데이터 병합 및 차이 계산
    merged_diff = pd.merge(
        boarding_df,
        alighting_df,
        on=['분기', '역명', '요일구분'],
        suffixes=('_승차', '_하차')
    )
    
    # 7. 시간대별 차이 계산
    for col in time_columns:
        merged_diff[f'{col}_diff'] = merged_diff[f'{col}_승차'] - merged_diff[f'{col}_하차']
    
    # 8. 결과 데이터프레임 생성
    diff_columns = ['분기', '역명', '요일구분'] + [f'{col}_diff' for col in time_columns]
    result_diff = merged_diff[diff_columns]
    
    # 9. 평균 차이 계산
    time_diff_cols = [col for col in result_diff.columns if col.endswith('_diff')]
    result_diff_avg = result_diff.groupby(['역명', '요일구분'])[time_diff_cols].mean().reset_index()
    
    # 10. 분기별 차이 비교 데이터 생성
    merged_comparison = pd.merge(
        result_diff,
        result_diff_avg,
        on=['역명', '요일구분'],
        suffixes=('', '_avg')
    )
    
    for col in time_diff_cols:
        merged_comparison[f'{col}_차이'] = merged_comparison[col] - merged_comparison[f'{col}_avg']
    
    result_comparison = merged_comparison[
        ['분기', '역명', '요일구분'] + 
        [f'{col}_차이' for col in time_diff_cols]
    ]
    
    return result_diff, result_diff_avg, result_comparison

In [39]:
df2024_diff, df2024_diff_avg, df2024_comparison = analyze_passenger_flow(df2024)

In [41]:
print(df2024_diff.shape, 33*3*4)
df2024_diff.head(10)

(396, 25) 396

,분기,역명,요일구분,연번_diff,06시 이전_diff,06시-07시_diff,07시-08시_diff,08시-09시_diff,09시-10시_diff,10시-11시_diff,...,16시-17시_diff,17시-18시_diff,18시-19시_diff,19시-20시_diff,20시-21시_diff,21시-22시_diff,22시-23시_diff,23시-24시_diff,24시 이후_diff,label_diff
0,2024Q1,가락시장,공휴일,-18,600,-344,568,1218,1531,1467,...,-635,-1280,-1156,-934,-1395,-1301,-1242,-1630,-339,0
1,2024Q1,가락시장,토요일,-12,810,-236,986,1109,1598,1538,...,-523,-1492,-1300,-728,-332,-856,-884,-1728,-346,0
2,2024Q1,가락시장,평일,-61,5225,2573,24034,-13439,3282,8559,...,2974,6732,7083,-16902,-6918,-5020,-9319,-5577,-3350,0
3,2024Q1,경복궁,공휴일,-18,637,-2419,-2594,-7367,-19474,-24736,...,18399,20585,15787,11536,9380,8558,3566,448,-199,0
4,2024Q1,경복궁,토요일,-12,581,-1201,-1798,-6642,-17086,-19265,...,13118,15641,14650,12229,12019,11530,7128,1179,-254,0
5,2024Q1,경복궁,평일,-61,1613,-19890,-69592,-308084,-137693,-70546,...,78183,128467,210944,56861,57672,60148,32211,8166,-1179,0
6,2024Q1,경찰병원,공휴일,-18,709,229,1150,1783,2217,2044,...,-1293,-1946,-1986,-1852,-1819,-1912,-1504,-1860,-255,0
7,2024Q1,경찰병원,토요일,-12,758,217,884,1747,2422,2299,...,-826,-1701,-1984,-1521,-1221,-1361,-1587,-1869,-208,0
8,2024Q1,경찰병원,평일,-61,5799,12134,37710,-5944,-3785,5085,...,2070,5093,-2026,-27163,-11318,-10447,-13696,-8791,-3702,0
9,2024Q1,고속터미널,공휴일,-18,543,-12416,-11908,-15684,-27514,-23389,...,12282,21104,26078,34481,51702,33499,19685,5010,138,0

In [43]:
print(df2024_diff_avg.shape, 33 * 3)
df2024_diff_avg.head(10)

(99, 24) 99

,역명,요일구분,연번_diff,06시 이전_diff,06시-07시_diff,07시-08시_diff,08시-09시_diff,09시-10시_diff,10시-11시_diff,11시-12시_diff,...,16시-17시_diff,17시-18시_diff,18시-19시_diff,19시-20시_diff,20시-21시_diff,21시-22시_diff,22시-23시_diff,23시-24시_diff,24시 이후_diff,label_diff
0,가락시장,공휴일,-17.25,690.25,-245.25,678.75,1513.00,1736.50,1539.50,995.50,...,-759.25,-1362.75,-1185.00,-1170.50,-1484.25,-1415.00,-1395.25,-1627.75,-274.00,0.0
1,가락시장,토요일,-12.75,952.00,-53.75,1189.75,1369.25,1847.00,1980.75,1535.00,...,-728.75,-1549.25,-1614.75,-789.00,-474.25,-811.50,-914.50,-1731.50,-348.00,0.0
2,가락시장,평일,-61.50,5433.50,3543.75,26100.25,-14962.25,4592.75,9555.50,6207.50,...,2171.00,4994.00,7343.75,-17087.50,-6395.25,-4405.50,-9457.75,-5394.25,-3544.75,0.0
3,경복궁,공휴일,-17.25,573.50,-1888.25,-3103.00,-9262.75,-22562.75,-26187.50,-24590.50,...,16454.00,19725.25,15196.75,11674.00,11320.25,9801.00,4004.00,291.00,-212.50,0.0
4,경복궁,토요일,-12.75,620.50,-1592.75,-2074.25,-8401.25,-20550.00,-21396.50,-21542.50,...,11410.00,16931.50,15936.50,12870.75,13831.75,12572.25,7193.25,1222.50,-253.00,0.0
5,경복궁,평일,-61.50,1341.00,-22142.00,-77476.50,-316780.25,-164422.00,-82937.00,-49400.50,...,86068.00,136016.00,205061.75,54710.75,62097.50,63556.25,35654.75,9653.75,-1145.50,0.0
6,경찰병원,공휴일,-17.25,798.25,265.00,1321.50,1815.25,2208.75,1991.50,1617.25,...,-1206.00,-1893.25,-2363.50,-1826.00,-1729.00,-2021.75,-1666.75,-1834.75,-223.25,0.0
7,경찰병원,토요일,-12.75,936.25,351.00,1059.00,1992.25,2670.00,2315.50,1902.75,...,-803.50,-1779.75,-2309.25,-1751.25,-1456.00,-1742.75,-1594.25,-2021.75,-233.00,0.0
8,경찰병원,평일,-61.50,6577.50,13366.25,39277.75,-7966.25,-3093.25,4999.50,8060.00,...,2595.50,4812.75,-3294.50,-27000.25,-11749.00,-10163.00,-13422.75,-8860.25,-3824.50,0.0
9,고속터미널,공휴일,-17.25,700.75,-12200.75,-10868.00,-14327.25,-26766.25,-22960.75,-19809.25,...,12278.25,18749.50,25915.75,34365.50,54613.25,36329.25,22108.50,5762.75,108.00,0.0

In [45]:
print(df2024_comparison.shape, 33*3*4)
df2024_comparison.head()

(396, 25) 396

,분기,역명,요일구분,연번_diff_차이,06시 이전_diff_차이,06시-07시_diff_차이,07시-08시_diff_차이,08시-09시_diff_차이,09시-10시_diff_차이,10시-11시_diff_차이,...,16시-17시_diff_차이,17시-18시_diff_차이,18시-19시_diff_차이,19시-20시_diff_차이,20시-21시_diff_차이,21시-22시_diff_차이,22시-23시_diff_차이,23시-24시_diff_차이,24시 이후_diff_차이,label_diff_차이
0,2024Q1,가락시장,공휴일,-0.75,-90.25,-98.75,-110.75,-295.00,-205.50,-72.50,...,124.25,82.75,29.00,236.50,89.25,114.00,153.25,-2.25,-65.00,0.0
1,2024Q1,가락시장,토요일,0.75,-142.00,-182.25,-203.75,-260.25,-249.00,-442.75,...,205.75,57.25,314.75,61.00,142.25,-44.50,30.50,3.50,2.00,0.0
2,2024Q1,가락시장,평일,0.50,-208.50,-970.75,-2066.25,1523.25,-1310.75,-996.50,...,803.00,1738.00,-260.75,185.50,-522.75,-614.50,138.75,-182.75,194.75,0.0
3,2024Q1,경복궁,공휴일,-0.75,63.50,-530.75,509.00,1895.75,3088.75,1451.50,...,1945.00,859.75,590.25,-138.00,-1940.25,-1243.00,-438.00,157.00,13.50,0.0
4,2024Q1,경복궁,토요일,0.75,-39.50,391.75,276.25,1759.25,3464.00,2131.50,...,1708.00,-1290.50,-1286.50,-641.75,-1812.75,-1042.25,-65.25,-43.50,-1.00,0.0

# Step 4. 최소제곱법을 이용하여 alpha 구하기

In [47]:
cong_2024 = pd.read_csv('2024년 3호선 지하철혼잡도_30분단위(평일, 토요일, 공휴일 구분)(전처리).csv')
cong_2024_1 = pd.read_csv('2024년 1분기 3호선 지하철혼잡도_30분단위(평일, 토요일, 공휴일 구분)(전처리).csv')
cong_2024_2 = pd.read_csv('2024년 2분기 3호선 지하철혼잡도_30분단위(평일, 토요일, 공휴일 구분)(전처리).csv')
cong_2024_3 = pd.read_csv('2024년 3분기 3호선 지하철혼잡도_30분단위(평일, 토요일, 공휴일 구분)(전처리).csv')
cong_2024_4 = pd.read_csv('2024년 4분기 3호선 지하철혼잡도_30분단위(평일, 토요일, 공휴일 구분)(전처리).csv')

In [49]:
def difference_congestion(cong_2024_1, cong_2024):
    # 공통 기준 컬럼과 시간대 컬럼 정의
    key_cols = ['요일구분', '호선', '출발역', '상하구분', '역번호']
    time_cols = [col for col in cong_2024_1.columns if col not in key_cols]

    # 두 데이터프레임 병합 (기준 컬럼으로)
    merged = pd.merge(cong_2024_1, cong_2024, on=key_cols, suffixes=('_1', '_2'))

    # 결과 데이터프레임 초기화 (기준 컬럼 복사)
    diff_df = merged[key_cols].copy()

    # 시간대별 차이 계산 (cong_2024_1 - cong_2024)
    for col in time_cols:
        diff_df[col] = merged[f'{col}_1'] - merged[f'{col}_2']

    return diff_df

In [51]:
cong_2024_1_diff = difference_congestion(cong_2024_1, cong_2024)
cong_2024_1_diff.head()

,요일구분,호선,출발역,상하구분,역번호,Unnamed: 0,6시 이전,6시00분,6시30분,7시00분,...,18시30분,19시00분,19시30분,20시00분,20시30분,21시00분,21시30분,22시00분,22시30분,23시 이후
0,일요일,3,지축,상선,33,-60,1.894860,0.388436,1.004299,0.837193,...,11.735438,8.714097,10.007805,6.506488,7.908291,5.642402,6.174598,6.591656,4.996796,8.7525
1,일요일,3,구파발,상선,32,-9,2.115895,0.388515,0.560628,0.344924,...,7.432924,4.206916,6.080013,3.505203,6.384946,6.367989,3.970780,3.579093,4.672874,1.1725
2,일요일,3,연신내,상선,31,-44,2.298477,0.799794,0.749239,0.656694,...,7.108859,5.967640,6.082170,5.068496,5.934169,7.652118,5.740451,4.386485,4.724294,1.9850
3,일요일,3,불광,상선,30,-29,1.647970,1.481715,0.662722,1.045915,...,9.276808,7.903474,7.598128,6.882011,8.521320,10.225040,7.018996,5.967544,5.001036,2.7650
4,일요일,3,녹번,상선,29,-12,0.995051,1.309317,0.411485,1.090609,...,8.867418,8.309645,7.085723,6.740926,9.139832,10.800841,7.417671,5.476610,5.262389,5.4425

In [53]:
cong_2024_2_diff = difference_congestion(cong_2024_2, cong_2024)
cong_2024_2_diff.head()

,요일구분,호선,출발역,상하구분,역번호,Unnamed: 0,6시 이전,6시00분,6시30분,7시00분,...,18시30분,19시00분,19시30분,20시00분,20시30분,21시00분,21시30분,22시00분,22시30분,23시 이후
0,일요일,3,지축,상선,33,-60,2.794860,2.088436,0.504299,1.837193,...,7.935438,5.514097,4.807805,4.906488,4.608291,4.242402,4.074598,8.291656,5.996796,6.1025
1,일요일,3,구파발,상선,32,-9,2.915895,2.388515,0.860628,0.744924,...,5.232924,2.706916,3.580013,2.905203,3.384946,4.667989,2.670780,4.079093,4.372874,0.8025
2,일요일,3,연신내,상선,31,-44,2.498477,3.099794,0.949239,1.156694,...,4.708859,4.067640,4.082170,3.768496,3.834169,5.052118,3.940451,5.886485,4.024294,1.2450
3,일요일,3,불광,상선,30,-29,2.547970,2.381715,0.862722,1.345915,...,5.976808,4.703474,5.598128,4.782011,5.321320,5.225040,6.218996,7.867544,5.501036,1.8050
4,일요일,3,녹번,상선,29,-12,2.595051,2.009317,0.911485,1.690609,...,6.767418,4.309645,5.585723,5.040926,6.639832,5.800841,6.017671,8.276610,5.462389,3.8925

In [55]:
cong_2024_3_diff = difference_congestion(cong_2024_3, cong_2024)
cong_2024_3_diff.head()

,요일구분,호선,출발역,상하구분,역번호,Unnamed: 0,6시 이전,6시00분,6시30분,7시00분,...,18시30분,19시00분,19시30분,20시00분,20시30분,21시00분,21시30분,22시00분,22시30분,23시 이후
0,일요일,3,지축,하선,33,-61,1.732075,-0.149572,1.244987,0.598065,...,-0.986009,0.103062,-1.696436,0.005637,-0.586495,-0.597502,-0.842692,-0.653839,-0.528860,-0.3750
1,일요일,3,구파발,하선,32,-10,-0.235937,0.479949,0.313357,0.368782,...,-0.606758,-0.119511,-0.592132,-0.100444,-0.951301,-0.835287,-0.409454,-0.655996,-0.645836,-0.4925
2,일요일,3,연신내,하선,31,-45,-0.224262,0.710882,0.509835,0.535977,...,-0.407709,0.008725,-0.227951,-0.408376,-1.246098,-0.789150,-0.094607,-0.862238,-0.484803,-0.5700
3,일요일,3,불광,하선,30,-30,-0.024215,0.878054,0.499746,0.471256,...,-0.219353,0.460184,-0.152697,-0.585596,-1.462183,-0.426499,-0.693377,-0.705354,-0.269900,-0.5275
4,일요일,3,녹번,하선,29,-13,0.174683,0.829846,0.474112,0.720717,...,-0.101872,0.420907,-0.297525,-0.390768,-1.534803,-0.229902,-0.725182,-0.424833,-0.410628,-0.4750

In [57]:
cong_2024_4_diff = difference_congestion(cong_2024_4, cong_2024)
cong_2024_4_diff.head()

,요일구분,호선,출발역,상하구분,역번호,Unnamed: 0,6시 이전,6시00분,6시30분,7시00분,...,18시30분,19시00분,19시30분,20시00분,20시30분,21시00분,21시30분,22시00분,22시30분,23시 이후
0,일요일,3,지축,상선,33,-60,2.715419,2.334692,2.787103,2.488420,...,11.793687,8.957709,9.676586,5.980536,7.775127,4.872795,5.276206,7.525032,4.409613,-0.4075
1,일요일,3,구파발,상선,32,-9,2.552316,2.434454,1.518115,0.965228,...,8.001229,4.579251,5.959962,3.184391,6.445162,4.896034,3.387659,4.062722,3.781377,0.8225
2,일요일,3,연신내,상선,31,-44,2.804569,2.400619,1.752284,1.429918,...,8.873422,6.797081,6.253490,5.094511,6.497494,5.943647,5.078648,3.540546,4.027118,1.8550
3,일요일,3,불광,상선,30,-29,2.756091,2.554854,1.811834,1.562254,...,10.569575,8.389578,7.505615,6.253966,7.736041,8.024881,6.343012,4.597367,5.096891,2.9950
4,일요일,3,녹번,상선,29,-12,2.614848,2.272049,1.765546,1.528173,...,10.797747,9.071066,7.442830,6.777221,7.580504,8.097478,6.446986,5.070170,4.912833,-0.2275

In [59]:
time_mapping = {
    '6시 이전': '06시 이전_diff_차이',
    '6시00분': '06시-07시_diff_차이', '6시30분': '06시-07시_diff_차이',
    '7시00분': '07시-08시_diff_차이', '7시30분': '07시-08시_diff_차이',
    '8시00분': '08시-09시_diff_차이', '8시30분': '08시-09시_diff_차이',
    '9시00분': '09시-10시_diff_차이', '9시30분': '09시-10시_diff_차이',
    '10시00분': '10시-11시_diff_차이', '10시30분': '10시-11시_diff_차이',
    '11시00분': '11시-12시_diff_차이', '11시30분': '11시-12시_diff_차이',
    '12시00분': '12시-13시_diff_차이', '12시30분': '12시-13시_diff_차이',
    '13시00분': '13시-14시_diff_차이', '13시30분': '13시-14시_diff_차이',
    '14시00분': '14시-15시_diff_차이', '14시30분': '14시-15시_diff_차이',
    '15시00분': '15시-16시_diff_차이', '15시30분': '15시-16시_diff_차이',
    '16시00분': '16시-17시_diff_차이', '16시30분': '16시-17시_diff_차이',
    '17시00분': '17시-18시_diff_차이', '17시30분': '17시-18시_diff_차이',
    '18시00분': '18시-19시_diff_차이', '18시30분': '18시-19시_diff_차이',
    '19시00분': '19시-20시_diff_차이', '19시30분': '19시-20시_diff_차이',
    '20시00분': '20시-21시_diff_차이', '20시30분': '20시-21시_diff_차이',
    '21시00분': '21시-22시_diff_차이', '21시30분': '21시-22시_diff_차이',
    '22시00분': '22시-23시_diff_차이', '22시30분': '22시-23시_diff_차이',
    '23시 이후': '23시-24시_diff_차이'
}

In [61]:
# alpha가 1개인 코드

def calculate_alpha_least_squares(df_comparison, cong_1_diff, cong_2_diff, cong_3_diff, cong_4_diff):
    
    # 1. 각 분기 데이터 정리 및 병합 준비
    cong_diffs = {
        '2024Q1': cong_1_diff,
        '2024Q2': cong_2_diff,
        '2024Q3': cong_3_diff, 
        '2024Q4': cong_4_diff
    }
    
    # 2. 데이터 저장용 리스트
    X_q_all = []
    Y_q_all = []
    
    # 3. 각 분기별로 처리
    for quarter, cong_diff in cong_diffs.items():
        # 분기별 Xq 데이터 필터링
        xq_df = df_comparison[df_comparison['분기'] == quarter]
        
        # 매핑 기준 설정 (역명→출발역, 요일구분은 공통)
        xq_keys = ['역명', '요일구분']
        yq_keys = ['출발역', '요일구분']
        
        # xq_df와 cong_diff(yq) 병합
        merged = pd.merge(
            xq_df, 
            cong_diff,
            left_on=xq_keys,
            right_on=yq_keys,
            suffixes=('_xq', '_yq')
        )
        
        # 각 혼잡도 시간대 컬럼에 대해
        for yq_col, xq_col in time_mapping.items():
            if yq_col in cong_diff.columns and xq_col in xq_df.columns:
                # 유효한 데이터만 추출
                valid_rows = merged[~merged[yq_col].isna() & ~merged[xq_col].isna()]
                
                # X_q, Y_q 값 추가
                X_q_all.extend(valid_rows[xq_col].values)
                Y_q_all.extend(valid_rows[yq_col].values)
    
    # 4. 배열로 변환
    X_q = np.array(X_q_all)
    Y_q = np.array(Y_q_all)
    
    # 5. 최소제곱법 수식으로 알파 계산
    alpha = np.sum(X_q * Y_q) / np.sum(X_q ** 2)
    
    return alpha, X_q, Y_q

In [65]:
from sklearn.metrics import r2_score

alpha, X_q, Y_q = calculate_alpha_least_squares(df2024_comparison, cong_2024_1_diff, cong_2024_2_diff, cong_2024_3_diff, cong_2024_4_diff)
print(alpha, X_q, Y_q)

r2 = r2_score(Y_q, alpha * X_q)
print(r2)

2.0215136213146077e-05 [-142.  -142.  -208.5 ... -261.5  413.   413. ] [ 1.46188663  0.          2.5084761  ...  0.47        4.9075
 -0.055     ]
-0.33995936198858456

In [69]:
# 시간대별로 alpha를 구하는 코드

def calculate_alpha_per_time(df_comparison, cong_1_diff, cong_2_diff, cong_3_diff, cong_4_diff):
    
    # 1. 각 분기 데이터 정리 및 병합 준비
    cong_diffs = {
        '2024Q1': cong_1_diff,
        '2024Q2': cong_2_diff,
        '2024Q3': cong_3_diff,
        '2024Q4': cong_4_diff
    }

    # 2. 시간대별 X, Y 모으기
    alpha_dict = {}
    for yq_col, xq_col in time_mapping.items():
        X_vals = []
        Y_vals = []

        for quarter, cong_diff in cong_diffs.items():
            # 분기별 Xq 필터
            xq_df = df_comparison[df_comparison['분기'] == quarter]
            merged = pd.merge(
                xq_df,
                cong_diff,
                left_on=['역명', '요일구분'],
                right_on=['출발역', '요일구분'],
                suffixes=('_xq', '_yq')
            )

            if yq_col in merged.columns and xq_col in merged.columns:
                valid = merged[[xq_col, yq_col]].dropna()
                X_vals.extend(valid[xq_col].values.flatten())
                Y_vals.extend(valid[yq_col].values.flatten())

        # 3. α 계산 (해당 시간대)
        X = np.array(X_vals)
        Y = np.array(Y_vals)
        denom = np.sum(X**2)
        if denom != 0:
            alpha_dict[yq_col] = np.sum(X * Y) / denom
        else:
            alpha_dict[yq_col] = np.nan  # 또는 0, 혹은 예외 처리

    return alpha_dict

In [71]:
alphas = calculate_alpha_per_time(df2024_comparison, cong_2024_1, cong_2024_2, cong_2024_3, cong_2024_4)

for time_slot, alpha in alphas.items():
    print(f"{time_slot}: α = {alpha:.6f}")

6시 이전: α = 0.000682
6시00분: α = 0.000012
6시30분: α = 0.000047
7시00분: α = 0.000182
7시30분: α = 0.000308
8시00분: α = 0.000257
8시30분: α = 0.000316
9시00분: α = -0.000033
9시30분: α = -0.000071
10시00분: α = -0.000272
10시30분: α = -0.000300
11시00분: α = -0.000621
11시30분: α = -0.000681
12시00분: α = -0.001091
12시30분: α = -0.001310
13시00분: α = -0.000465
13시30분: α = -0.000554
14시00분: α = 0.000602
14시30분: α = 0.000685
15시00분: α = 0.000416
15시30분: α = 0.000342
16시00분: α = 0.000429
16시30분: α = 0.000401
17시00분: α = -0.000180
17시30분: α = -0.000226
18시00분: α = -0.000293
18시30분: α = -0.000228
19시00분: α = 0.000047
19시30분: α = 0.000042
20시00분: α = 0.000697
20시30분: α = 0.000647
21시00분: α = 0.000660
21시30분: α = 0.000576
22시00분: α = 0.000331
22시30분: α = 0.000307
23시 이후: α = -0.000135

In [73]:
# alpha별로 R^2을 구하는 코드

def calculate_r_squared_per_time(alpha_dict, df_comparison, cong_1_diff, cong_2_diff, cong_3_diff, cong_4_diff):
    
    cong_diffs = {
        '2024Q1': cong_1_diff,
        '2024Q2': cong_2_diff,
        '2024Q3': cong_3_diff,
        '2024Q4': cong_4_diff
    }
    
    r_squared_dict = {}

    for yq_col, xq_col in time_mapping.items():
        alpha = alpha_dict.get(yq_col, None)
        if alpha is None or np.isnan(alpha):
            r_squared_dict[yq_col] = np.nan
            continue
        
        X_vals = []
        Y_vals = []
        for quarter, cong_diff in cong_diffs.items():
            xq_df = df_comparison[df_comparison['분기'] == quarter]
            merged = pd.merge(
                xq_df,
                cong_diff,
                left_on=['역명', '요일구분'],
                right_on=['출발역', '요일구분'],
                suffixes=('_xq', '_yq')
            )
            if yq_col in merged.columns and xq_col in merged.columns:
                valid = merged[[xq_col, yq_col]].dropna()
                X_vals.extend(valid[xq_col].values.flatten())
                Y_vals.extend(valid[yq_col].values.flatten())
        
        X = np.array(X_vals)
        Y = np.array(Y_vals)
        
        if len(X) == 0 or len(Y) == 0:
            r_squared_dict[yq_col] = np.nan
            continue
        
        Y_pred = alpha * X
        
        ss_res = np.sum((Y - Y_pred) ** 2)
        ss_tot = np.sum((Y - np.mean(Y)) ** 2)
        
        # R^2 계산 (총변동 대비 설명된 변동)
        r2 = 1 - ss_res / ss_tot if ss_tot != 0 else np.nan
        r_squared_dict[yq_col] = r2
    
    return r_squared_dict

In [77]:
r2s = calculate_r_squared_per_time(
    alpha_dict=alphas,
    df_comparison=df2024_comparison,
    cong_1_diff=cong_2024_1,
    cong_2_diff=cong_2024_2,
    cong_3_diff=cong_2024_3,
    cong_4_diff=cong_2024_4
)

r2s = calculate_r_squared_per_time(alpha_dict=alphas, df_comparison=df2024_comparison, cong_1_diff=cong_2024_1, 
                                   cong_2_diff=cong_2024_2, cong_3_diff=cong_2024_3, cong_4_diff=cong_2024_4)

sum(r2s.values()) / len(r2s.values())

-3.086574951650471

In [79]:
def calculate_alpha_and_r2_by_station(df_comparison, cong_1_diff, cong_2_diff, cong_3_diff, cong_4_diff, single_station_list):
    cong_diffs = {
        '2024Q1': cong_1_diff,
        '2024Q2': cong_2_diff,
        '2024Q3': cong_3_diff,
        '2024Q4': cong_4_diff
    }

    # 결과 저장용 딕셔너리
    station_results = {}

    # 역별 처리
    for station in single_station_list:
        X_total = []
        Y_total = []

        # 해당 역에 대한 데이터 수집
        for quarter, cong_diff in cong_diffs.items():
            xq_df = df_comparison[(df_comparison['분기'] == quarter) & 
                                (df_comparison['역명'] == station)]
            
            cong_df = cong_diff[cong_diff['출발역'] == station]

            merged = pd.merge(
                xq_df,
                cong_df,
                left_on=['역명', '요일구분'],
                right_on=['출발역', '요일구분'],
                suffixes=('_xq', '_yq')
            )

            for y_col, x_col in time_mapping.items():
                if y_col in merged.columns and x_col in merged.columns:
                    valid = merged[[x_col, y_col]].dropna()
                    X_total.extend(valid[x_col].values)
                    Y_total.extend(valid[y_col].values)

        # 역별 계산
        X_total = np.array(X_total)
        Y_total = np.array(Y_total)

        if len(X_total) > 0:
            denom = np.sum(X_total ** 2)
            alpha = np.sum(X_total * Y_total) / denom if denom != 0 else np.nan
            
            Y_pred = alpha * X_total
            ss_res = np.sum((Y_total - Y_pred) ** 2)
            ss_tot = np.sum((Y_total - np.mean(Y_total)) ** 2)
            r2 = 1 - (ss_res / ss_tot) if ss_tot != 0 else np.nan
        else:
            alpha, r2 = np.nan, np.nan

        station_results[station] = (alpha, r2)

    return station_results

In [83]:
station_order = [
    '오금', '경찰병원', '가락시장', '수서', '일원', '대청', '학여울', '대치', '도곡', '매봉',
    '양재', '남부터미널', '교대', '고속터미널', '잠원', '신사', '압구정', '옥수', '금호',
    '약수', '동대입구', '충무로', '을지로3가', '종로3가', '안국', '경복궁', '독립문',
    '무악재', '홍제', '녹번', '불광', '연신내', '구파발', '지축', '삼송', '원흥', '원당',
    '화정', '대곡', '백석', '마두', '정발산', '주엽', '대화'
]

# 함수 실행
result = calculate_alpha_and_r2_by_station(
    df2024_comparison,
    cong_2024_1, cong_2024_2,
    cong_2024_3, cong_2024_4,
    station_order
)

r2_values = [v[1] for v in result.values() if not np.isnan(v[1])]
mean_r2 = np.mean(r2_values) if len(r2_values) > 0 else np.nan
mean_r2

-4.1276554247715165

# 수정된 모델 학습 방법

# Step 1. 지하철 혼잡도 데이터 전처리

In [85]:
import numpy as np
import pandas as pd

df_2022_11 = pd.read_csv('2022년 4분기 열차혼잡도.csv', encoding = 'cp949')
df_2023_11 = pd.read_csv('2023년 4분기 열차혼잡도.csv', encoding = 'cp949')
df_2024_11 = pd.read_excel('2024년 4분기 열차혼잡도.xlsx')

stations = [
    "장암", "도봉산", "수락산", "마들", "노원", "중계", "하계", "공릉", "태릉입구", "먹골", "중화", "상봉", "면목", "사가정", "용마산",
    "중곡", "군자", "어린이대공원", "건대입구", "뚝섬유원지", "청담", "강남구청", "학동", "논현", "반포", "고속터미널", "내방", "이수",
    "남성", "숭실대입구", "상도", "장승배기", "신대방삼거리", "보라매", "신풍", "대림", "남구로", "가산디지털단지", "철산", "광명사거리",
    "천왕", "온수"
]

In [87]:
df_2024_09 = pd.read_excel('2024년 3분기 구간별 열차혼잡도.xlsx')

In [91]:
df_2024_03 = pd.read_csv('서울교통공사_지하철혼잡도정보_20240331.csv', encoding = 'cp949')
df_2024_06 = pd.read_csv('서울교통공사_지하철혼잡도정보_20240630.csv', encoding = 'cp949')

In [93]:
def preprocess_congestion_data(df, line=7, stations=None):
    # 호선 필터링
    filtered_df = df[df['호선'] == line].copy()
    
    # 역명 클렌징(괄호 내용 제거)
    filtered_df['출발역'] = filtered_df['출발역'].str.replace(r'\(.*\)', '', regex=True).str.strip()
    
    # 온수를 0, 이후 역순으로 1씩 증가
    if stations:
        reversed_stations = stations[::-1]  # 리스트 역순
        station_label = {station: idx for idx, station in enumerate(reversed_stations)}
        filtered_df['label'] = filtered_df['출발역'].map(station_label).fillna(-1).astype(int)
    else:
        filtered_df['label'] = -1

    filtered_df = filtered_df.sort_values(
        ['label', '상하구분'], 
        ascending=[True, True]
    ).reset_index(drop=True)
    
    return filtered_df

In [95]:
# 2022년 데이터 전처리
congestion_2022 = preprocess_congestion_data(df_2022_11, stations=stations)

# 2023년 데이터 전처리
congestion_2023 = preprocess_congestion_data(df_2023_11, stations=stations)

# 2024년 데이터 전처리
congestion_2024 = preprocess_congestion_data(df_2024_11, stations=stations)

In [97]:
congestion_2024_09 = preprocess_congestion_data(df_2024_09, stations=stations)
congestion_2024_03 = preprocess_congestion_data(df_2024_03, stations=stations)
congestion_2024_06 = preprocess_congestion_data(df_2024_06, stations=stations)

In [99]:
congestion_2024_06

,연번,요일구분,호선,역번호,출발역,상하구분,6시00분,6시30분,7시00분,7시30분,...,20시30분,21시00분,21시30분,22시00분,22시30분,23시00분,23시30분,00시00분,00시30분,label
0,519,평일,7,2752,온수,상선,33.8,55.7,66.3,91.6,...,16.7,11.6,15.0,16.6,12.6,14.8,7.3,6.0,0.0,0
1,1075,토요일,7,2752,온수,상선,20.0,17.8,18.4,22.9,...,19.7,12.0,12.2,19.5,15.8,12.0,5.6,0.0,NaN,0
2,1631,일요일,7,2752,온수,상선,9.3,10.4,9.6,11.4,...,19.4,13.4,13.2,17.2,10.3,7.4,2.4,0.0,NaN,0
3,520,평일,7,2752,온수,하선,16.0,8.8,15.1,26.0,...,25.3,42.1,27.2,34.7,33.6,46.0,17.4,18.2,8.4,0
4,1076,토요일,7,2752,온수,하선,14.1,17.1,8.6,17.3,...,25.8,31.5,23.2,26.5,24.1,26.1,17.6,0.0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,993,토요일,7,2711,장암,상선,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,41
248,1549,일요일,7,2711,장암,상선,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,41
249,438,평일,7,2711,장암,하선,5.4,7.3,12.1,17.5,...,0.9,0.7,1.0,0.5,0.5,0.2,0.1,0.1,NaN,41
250,994,토요일,7,2711,장암,하선,1.4,0.8,1.5,3.7,...,0.6,0.8,1.2,0.4,0.3,0.2,0.0,0.0,NaN,41
251,1550,일요일,7,2711,장암,하선,0.8,0.6,0.8,1.4,...,0.7,1.0,0.5,0.2,0.4,0.2,0.0,0.0,NaN,41

In [101]:
congestion_2023

,요일구분,호선,출발역,상하구분,6시00분,6시30분,7시00분,7시30분,8시00분,8시30분,...,19시30분,20시00분,20시30분,21시00분,21시30분,22시00분,22시30분,23시00분,23시30분,label
0,평일,7,온수,상선,33.6,51.7,63.9,87.1,105.6,81.8,...,15.1,14.6,14.9,11.1,13.7,14.3,11.0,13.8,7.2,0
1,토요일,7,온수,상선,20.1,17.2,17.6,19.0,36.6,38.2,...,12.0,14.9,13.1,10.8,11.3,16.9,14.6,13.5,4.9,0
2,일요일,7,온수,상선,10.2,10.5,9.4,10.7,19.7,25.1,...,13.0,15.3,11.8,10.9,10.3,12.6,10.5,7.4,3.2,0
3,평일,7,온수,하선,15.8,8.4,14.2,24.7,39.4,15.6,...,54.8,35.4,25.9,40.3,26.8,34.7,34.9,42.0,19.1,0
4,토요일,7,온수,하선,14.3,15.0,8.3,15.2,10.2,12.5,...,33.1,21.3,23.7,35.2,21.7,28.8,25.5,28.2,19.7,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,토요일,7,장암,상선,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41
248,일요일,7,장암,상선,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41
249,평일,7,장암,하선,4.8,7.6,10.9,16.2,10.3,5.5,...,0.6,0.5,0.5,0.4,0.5,0.6,0.3,0.2,0.1,41
250,토요일,7,장암,하선,0.7,1.8,1.8,2.4,3.3,2.2,...,0.7,0.8,1.2,0.3,0.6,0.2,0.5,0.4,0.1,41
251,일요일,7,장암,하선,0.3,0.6,0.6,2.0,1.1,1.0,...,1.0,0.5,0.7,0.7,0.6,0.5,0.2,0.2,0.0,41

In [103]:
def convert_hourly_congestion(df):
    
    # 시간대 컬럼 추출 및 정렬
    time_columns = sorted([col for col in df.columns if '시' in col], 
                         key=lambda x: int(x.split('시')[0]))
    
    # 1시간 단위 그룹 생성
    hourly_groups = []
    for i in range(0, len(time_columns), 2):
        group = time_columns[i:i+2]
        if len(group) == 2:
            hourly_groups.append(group)
    
    # 새로운 컬럼명 매핑 (06 ~ 07 형식)
    new_columns = [f"{int(group[0].split('시')[0]):02d} ~ {int(group[0].split('시')[0])+1:02d}" 
                  for group in hourly_groups]
    
    # 평균 계산
    aggregated = {}
    for new_col, cols in zip(new_columns, hourly_groups):
        aggregated[new_col] = df[cols].mean(axis=1)
    
    # 최종 데이터프레임 생성
    result_df = pd.DataFrame({
        'label': df['label'],
        '역명': df['출발역'],
        '구분': df['상하구분'],
        '요일구분': df['요일구분']
    })
    
    for col in new_columns:
        result_df[col] = aggregated[col]
    
    return result_df

congestion_2022_hourly = convert_hourly_congestion(congestion_2022)
congestion_2023_hourly = convert_hourly_congestion(congestion_2023)
congestion_2024_hourly = convert_hourly_congestion(congestion_2024)

In [105]:
congestion_2024_09_hourly = convert_hourly_congestion(congestion_2024_09)
congestion_2024_03_hourly = convert_hourly_congestion(congestion_2024_03)
congestion_2024_06_hourly = convert_hourly_congestion(congestion_2024_06)

congestion_2024_03_hourly

,label,역명,구분,요일구분,06 ~ 07,07 ~ 08,08 ~ 09,09 ~ 10,10 ~ 11,11 ~ 12,...,15 ~ 16,16 ~ 17,17 ~ 18,18 ~ 19,19 ~ 20,20 ~ 21,21 ~ 22,22 ~ 23,23 ~ 24,24 ~ 25
0,0,온수,상선,평일,42.90,79.75,95.20,62.05,29.40,23.80,...,18.40,22.40,22.45,23.65,17.90,15.40,12.70,14.75,10.15,3.0
1,0,온수,상선,토요일,17.40,19.85,40.10,33.25,37.20,40.05,...,29.15,34.55,27.60,25.65,14.35,17.20,12.15,16.55,9.40,0.0
2,0,온수,상선,일요일,9.75,10.90,23.70,27.50,33.00,31.50,...,23.85,24.90,18.95,21.30,15.35,15.90,10.60,12.70,5.85,0.0
3,0,온수,하선,평일,11.65,20.50,26.80,9.10,12.60,12.85,...,25.40,37.05,63.75,99.05,52.80,31.30,35.20,35.95,32.70,13.1
4,0,온수,하선,토요일,14.15,12.20,12.70,19.90,18.75,24.40,...,27.85,38.40,43.20,33.95,34.10,25.45,30.80,29.10,25.65,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,41,장암,상선,토요일,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN
248,41,장암,상선,일요일,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN
249,41,장암,하선,평일,5.95,14.50,8.40,3.95,1.60,1.30,...,1.55,1.55,2.00,1.75,0.95,0.50,0.70,0.35,0.10,0.0
250,41,장암,하선,토요일,1.35,2.85,3.05,3.15,2.45,2.50,...,4.85,3.55,3.30,2.70,1.75,1.25,1.40,0.20,0.10,0.0
251,41,장암,하선,일요일,0.60,1.65,1.65,1.70,1.45,1.90,...,3.55,2.65,2.75,2.90,1.75,1.00,0.80,0.30,0.10,0.0

In [107]:
congestion_2022_hourly.to_csv('2022년 11월 역별 시간대별 혼잡도(전처리).csv')
congestion_2023_hourly.to_csv('2023년 11월 역별 시간대별 혼잡도(전처리).csv')
congestion_2024_hourly.to_csv('2024년 11월 역별 시간대별 혼잡도(전처리).csv')

In [109]:
congestion_2024_hourly

,label,역명,구분,요일구분,06 ~ 07,07 ~ 08,08 ~ 09,09 ~ 10,10 ~ 11,11 ~ 12,...,14 ~ 15,15 ~ 16,16 ~ 17,17 ~ 18,18 ~ 19,19 ~ 20,20 ~ 21,21 ~ 22,22 ~ 23,23 ~ 24
0,0,온수,상선,평일,43.698547,76.161757,93.127617,62.725617,28.939689,24.171444,...,17.654525,18.865313,22.270303,22.428455,22.811007,16.156493,14.741259,11.978835,13.109159,10.224478
1,0,온수,상선,토요일,19.036624,19.864252,39.244825,35.191481,36.351911,39.314889,...,28.298169,30.407643,34.620621,25.507564,21.961783,13.676752,14.665207,11.369427,15.729830,8.334660
2,0,온수,상선,일요일,10.703291,10.932524,24.133658,27.188495,32.961783,30.072154,...,22.578125,23.580812,24.685012,18.163814,18.439988,14.603901,14.433221,9.994526,11.037022,5.015924
3,0,온수,하선,평일,11.888672,19.945808,26.597672,9.203472,12.610525,12.784037,...,19.125000,25.765791,37.432657,65.202495,91.550510,51.360825,31.147868,34.017317,33.542330,30.804693
4,0,온수,하선,토요일,13.779193,10.733148,11.761146,18.992038,16.900080,21.746815,...,30.722134,29.977309,39.452229,45.351911,34.879777,34.289013,25.110669,30.656051,27.679140,23.873408
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,41,장암,상선,토요일,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
248,41,장암,상선,일요일,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
249,41,장암,하선,평일,6.088940,13.648211,8.242989,3.922008,1.777026,1.211463,...,1.504003,1.604244,1.707526,2.029647,1.956111,0.977530,0.570926,0.593485,0.438727,0.282643
250,41,장암,하선,토요일,0.911624,2.834395,3.093153,2.797240,2.376592,1.957272,...,3.251062,3.957006,3.853503,3.128981,2.365977,1.577760,0.995223,0.919586,0.537420,0.358280
251,41,장암,하선,일요일,0.741441,1.348527,1.263933,1.786425,1.517715,1.681927,...,3.270966,4.015725,3.738721,3.050358,2.499668,1.559183,0.840963,0.860868,0.338376,0.159236

# Step 2. 지하철 승하차 인원 데이터 전처리

In [112]:
import numpy as np
import pandas as pd
from datetime import datetime
import holidays
import re

df_2022_11 = pd.read_excel('2022년 11월 역별 시간대별 이용인원.xlsx')
df_2023_11 = pd.read_excel('2023년 11월 역별 시간대별 이용인원.xlsx')
df_2024_11 = pd.read_excel('2024년 11월 역별 시간대별 이용인원.xlsx')

stations = [
    "장암", "도봉산", "수락산", "마들", "노원", "중계", "하계", "공릉", "태릉입구", "먹골", "중화", "상봉", "면목", "사가정", "용마산",
    "중곡", "군자", "어린이대공원", "건대입구", "뚝섬유원지", "청담", "강남구청", "학동", "논현", "반포", "고속터미널", "내방", "이수",
    "남성", "숭실대입구", "상도", "장승배기", "신대방삼거리", "보라매", "신풍", "대림", "남구로", "가산디지털단지", "철산", "광명사거리",
    "천왕", "온수"]

In [113]:
df_2024_09 = pd.read_excel('2024년 9월 역별 시간대별 이용인원.xlsx')
df_2024_03 = pd.read_excel('2024년 3월 역별 시간대별 이용인원.xlsx')
df_2024_06 = pd.read_excel('2024년 6월 역별 시간대별 이용인원.xlsx')

In [114]:
def process_subway_data(df, start_date, end_date, line='7호선'):
    
    # 필터링 조건 적용
    mask = (
        (df['호선'] == line) &
        (df['날짜'] >= start_date) &
        (df['날짜'] <= end_date)
    )
    filtered_df = df[mask].copy()

    filtered_df = filtered_df.drop(columns=['역번호', '06시 이전', '24시 이후'], errors='ignore')

    start_year = pd.to_datetime(start_date).year
    end_year = pd.to_datetime(end_date).year
    kr_holidays = holidays.KR(years=range(start_year, end_year+1))

    # 요일 구분 함수
    def get_day_type(date):
        if date in kr_holidays or date.weekday() == 6:
            return '공휴일'
        elif date.weekday() == 5:
            return '토요일'
        else:
            return '평일'
    # 요일 구분 컬럼 추가
    filtered_df['요일구분'] = filtered_df['날짜'].apply(get_day_type)
    
    # 역명 클렌징(괄호 내용 제거 및 공백 정리)
    filtered_df['역명'] = filtered_df['역명'].str.replace(r'\(.*\)', '', regex=True).str.strip()
    
    # 표준 역 순서 및 레이블 매핑
    station_label = {station:idx for idx, station in enumerate(stations)}
    
    # 레이블 부여 및 정렬
    if stations:
        reversed_stations = stations[::-1]  # 리스트 역순
        station_label = {station: idx for idx, station in enumerate(reversed_stations)}
        filtered_df['label'] = filtered_df['역명'].map(station_label).fillna(-1).astype(int)
    else:
        filtered_df['label'] = -1
    filtered_df = filtered_df.sort_values(
        ['날짜', 'label', '구분'], 
        ascending=[True, True, True]
    ).reset_index(drop=True)
    
    return filtered_df

In [115]:
df_2024_09_processed = process_subway_data(df_2024_09, start_date='2024-09-23', end_date='2024-09-29')
df_2024_03_processed = process_subway_data(df_2024_03, start_date='2024-03-18', end_date='2024-03-24')
df_2024_06_processed = process_subway_data(df_2024_06, start_date='2024-06-17', end_date='2024-06-23')

In [116]:
df_2024_03_processed

,날짜,호선,역명,구분,06 ~ 07,07 ~ 08,08 ~ 09,09 ~ 10,10 ~ 11,11 ~ 12,...,17 ~ 18,18 ~ 19,19 ~ 20,20 ~ 21,21 ~ 22,22 ~ 23,23 ~ 24,합 계,요일구분,label
0,2024-03-18,7호선,온수,승차,845,2157,2315,866,429,361,...,666,577,242,189,213,109,64,11643,평일,0
1,2024-03-18,7호선,온수,하차,154,549,818,338,245,354,...,961,1687,1333,888,484,547,296,10810,평일,0
2,2024-03-18,7호선,천왕,승차,877,2582,2641,1296,636,467,...,563,590,269,181,142,94,59,13276,평일,1
3,2024-03-18,7호선,천왕,하차,224,446,864,334,251,292,...,1198,2138,1821,935,672,592,328,12930,평일,1
4,2024-03-18,7호선,광명사거리,승차,1319,3421,3768,1834,1009,873,...,1204,1168,737,509,366,239,98,22334,평일,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583,2024-03-24,7호선,수락산,하차,82,187,364,893,861,525,...,666,643,543,441,470,384,223,9074,공휴일,39
584,2024-03-24,7호선,도봉산,승차,113,214,342,435,413,368,...,469,394,233,176,95,61,30,6203,공휴일,40
585,2024-03-24,7호선,도봉산,하차,124,164,313,968,939,847,...,455,425,489,382,455,385,245,8887,공휴일,40
586,2024-03-24,7호선,장암,승차,35,51,98,87,92,107,...,179,163,100,46,38,14,5,1927,공휴일,41
587,2024-03-24,7호선,장암,하차,23,26,77,137,194,128,...,68,65,31,42,27,18,13,1294,공휴일,41

In [117]:
df_2022_processed = process_subway_data(df_2022_11, start_date='2022-11-07', end_date='2022-11-13')
df_2023_processed = process_subway_data(df_2023_11, start_date='2023-11-07', end_date='2023-11-13') 
df_2024_processed = process_subway_data(df_2024_11, start_date='2024-11-01', end_date='2024-11-30')

In [118]:
df_2024_processed

,날짜,호선,역명,구분,06 ~ 07,07 ~ 08,08 ~ 09,09 ~ 10,10 ~ 11,11 ~ 12,...,17 ~ 18,18 ~ 19,19 ~ 20,20 ~ 21,21 ~ 22,22 ~ 23,23 ~ 24,합 계,요일구분,label
0,2024-11-01,7호선,온수,승차,820,1978,2297,889,439,432,...,657,570,265,183,167,122,101,11914,평일,0
1,2024-11-01,7호선,온수,하차,161,489,756,527,345,291,...,884,1601,1105,716,503,506,347,10761,평일,0
2,2024-11-01,7호선,천왕,승차,814,2349,2439,1263,650,506,...,754,639,308,220,163,124,56,13219,평일,1
3,2024-11-01,7호선,천왕,하차,268,421,863,282,265,377,...,1278,1933,1401,786,637,607,465,12747,평일,1
4,2024-11-01,7호선,광명사거리,승차,1282,3306,3481,1599,991,983,...,1574,1349,878,467,437,384,188,23104,평일,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2515,2024-11-30,7호선,수락산,하차,163,186,336,526,655,600,...,907,860,592,645,608,558,376,10587,토요일,39
2516,2024-11-30,7호선,도봉산,승차,229,398,604,554,524,552,...,402,253,138,123,103,76,28,6843,토요일,40
2517,2024-11-30,7호선,도봉산,하차,126,175,344,581,555,510,...,676,615,500,475,541,510,416,8910,토요일,40
2518,2024-11-30,7호선,장암,승차,39,92,162,143,126,99,...,121,91,64,51,25,25,9,1900,토요일,41
2519,2024-11-30,7호선,장암,하차,38,48,57,109,136,98,...,106,59,45,55,35,42,21,1330,토요일,41

In [119]:
def aggregate_time_data(df_list):
    results = {}
    
    for idx, df in enumerate(df_list, start=2022):
        # 시간대 컬럼 추출
        time_columns = [col for col in df.columns if '~' in col]
        
        # 그룹핑 및 집계
        agg_df = df.groupby(
            ['label', '역명','구분', '요일구분'], 
            as_index=False
        )[time_columns].mean()
        
        results[f'{idx}_agg'] = agg_df
    
    return results

In [120]:
# 입력 데이터 준비
processed_data = [df_2022_processed, df_2023_processed, df_2024_processed, df_2024_09_processed, df_2024_03_processed, df_2024_06_processed]

# 집계 실행
aggregated_results = aggregate_time_data(processed_data)

# 결과 확인
df_2022_agg = aggregated_results['2022_agg']
df_2023_agg = aggregated_results['2023_agg'] 
df_2024_agg = aggregated_results['2024_agg']
df_2024_09_agg = aggregated_results['2025_agg']
df_2024_03_agg = aggregated_results['2026_agg']
df_2024_06_agg = aggregated_results['2027_agg']

In [122]:
df_2022_agg

,label,역명,구분,요일구분,06 ~ 07,07 ~ 08,08 ~ 09,09 ~ 10,10 ~ 11,11 ~ 12,...,14 ~ 15,15 ~ 16,16 ~ 17,17 ~ 18,18 ~ 19,19 ~ 20,20 ~ 21,21 ~ 22,22 ~ 23,23 ~ 24
0,0,온수,승차,공휴일,129.0,172.0,297.0,400.0,387.0,339.0,...,293.0,306.0,229.0,215.0,207.0,175.0,123.0,89.0,81.0,33.0
1,0,온수,승차,토요일,217.0,368.0,647.0,530.0,465.0,471.0,...,335.0,351.0,343.0,323.0,231.0,131.0,116.0,92.0,104.0,25.0
2,0,온수,승차,평일,761.8,2274.2,2660.6,1024.8,477.2,421.2,...,423.6,475.2,824.0,760.0,617.4,255.2,191.2,175.2,129.4,62.8
3,0,온수,하차,공휴일,64.0,80.0,190.0,164.0,203.0,139.0,...,262.0,274.0,342.0,385.0,409.0,292.0,304.0,301.0,266.0,192.0
4,0,온수,하차,토요일,106.0,119.0,185.0,218.0,237.0,206.0,...,424.0,363.0,418.0,468.0,533.0,405.0,340.0,372.0,399.0,295.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,41,장암,승차,토요일,35.0,91.0,140.0,134.0,108.0,103.0,...,160.0,142.0,173.0,160.0,81.0,53.0,26.0,32.0,14.0,4.0
248,41,장암,승차,평일,325.2,793.8,477.8,176.2,72.2,67.6,...,79.6,90.6,117.4,118.6,97.8,59.4,25.4,25.8,13.4,6.4
249,41,장암,하차,공휴일,14.0,38.0,45.0,76.0,66.0,83.0,...,36.0,42.0,30.0,63.0,42.0,27.0,32.0,15.0,20.0,10.0
250,41,장암,하차,토요일,36.0,44.0,92.0,97.0,99.0,105.0,...,64.0,73.0,48.0,88.0,61.0,45.0,47.0,31.0,36.0,15.0
251,41,장암,하차,평일,57.6,40.0,60.2,49.4,46.4,67.2,...,48.6,45.2,50.2,68.8,152.4,131.8,75.4,32.0,33.4,20.4

In [136]:
df_2022_agg.to_csv('2022년 11월 역별 시간대별 승하차인원(전처리).csv')
df_2023_agg.to_csv('2023년 11월 역별 시간대별 승하차인원(전처리).csv')
df_2024_agg.to_csv('2024년 11월 역별 시간대별 승하차인원(전처리).csv')

# Step 3. 지하철 승하차 데이터 모델 학습을 위한 Input 형태로 변경

In [138]:
import numpy as np
import pandas as pd

inout_22 = pd.read_csv('2022년 11월 역별 시간대별 승하차인원(전처리).csv', index_col=0)
inout_23 = pd.read_csv('2023년 11월 역별 시간대별 승하차인원(전처리).csv', index_col=0)
inout_24 = pd.read_csv('2024년 11월 역별 시간대별 승하차인원(전처리).csv', index_col=0)

In [140]:
inout_24_09 = df_2024_09_agg.copy()
inout_24_03 = df_2024_03_agg.copy()
inout_24_06 = df_2024_06_agg.copy()

In [142]:
time_cols = ['06 ~ 07', '07 ~ 08', '08 ~ 09', '09 ~ 10',
             '10 ~ 11', '11 ~ 12', '12 ~ 13', '13 ~ 14', '14 ~ 15', '15 ~ 16',
             '16 ~ 17', '17 ~ 18', '18 ~ 19', '19 ~ 20', '20 ~ 21', '21 ~ 22',
             '22 ~ 23', '23 ~ 24']

In [144]:
def time_onehot(df, time_cols):

    # 1. melt로 시간대별로 행을 늘림
    id_vars = [col for col in df.columns if col not in time_cols]
    df_melt = df.melt(
        id_vars=id_vars,
        value_vars=time_cols,
        var_name='시간대',
        value_name='인원수'
    )
    
    # 2. 구분(승차/하차)을 컬럼으로 피벗
    df_pivot = df_melt.pivot_table(
        index=[col for col in df_melt.columns if col not in ['구분', '인원수']],
        columns='구분',
        values='인원수',
        aggfunc='sum'  # 중복 시 합계 계산
    ).reset_index()
    
    # 3. 컬럼명 정리
    df_pivot.columns = [col if col == '시간대' else f'{col}' for col in df_pivot.columns]
    
    # 4. 시간대 원핫 인코딩
    df_final = pd.get_dummies(df_pivot, columns=['시간대', '요일구분'])
    
    
    return df_final

inout_22_ohe = time_onehot(inout_22, time_cols)
inout_23_ohe = time_onehot(inout_23, time_cols)
inout_24_ohe = time_onehot(inout_24, time_cols)
inout_24_09_ohe = time_onehot(inout_24_09, time_cols)
inout_24_03_ohe = time_onehot(inout_24_03, time_cols)
inout_24_06_ohe = time_onehot(inout_24_06, time_cols)

In [146]:
inout_22_ohe.to_csv('2022년 11월 역별 시간대별 승하차인원(ohe).csv')
inout_23_ohe.to_csv('2023년 11월 역별 시간대별 승하차인원(ohe).csv')
inout_24_ohe.to_csv('2024년 11월 역별 시간대별 승하차인원(ohe).csv')

In [148]:
inout_24_ohe

,label,역명,승차,하차,시간대_06 ~ 07,시간대_07 ~ 08,시간대_08 ~ 09,시간대_09 ~ 10,시간대_10 ~ 11,시간대_11 ~ 12,...,시간대_17 ~ 18,시간대_18 ~ 19,시간대_19 ~ 20,시간대_20 ~ 21,시간대_21 ~ 22,시간대_22 ~ 23,시간대_23 ~ 24,요일구분_공휴일,요일구분_토요일,요일구분_평일
0,0,온수,118.000000,69.000000,True,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,0,온수,187.750000,124.500000,False,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,0,온수,356.250000,195.000000,False,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,0,온수,437.750000,237.000000,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
4,0,온수,447.250000,272.000000,False,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2263,41,장암,53.523810,147.142857,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,True
2264,41,장암,36.428571,82.809524,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,True
2265,41,장암,23.095238,34.333333,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
2266,41,장암,16.142857,42.904762,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
2267,41,장암,9.857143,25.238095,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True

In [150]:
def time_label(df, time_cols, time_col_name='시간대', value_col_name='인원수', inout_col='구분'):
    
    # 1. melt로 시간대별 행 확장
    id_vars = [col for col in df.columns if col not in time_cols]
    df_melt = df.melt(
        id_vars=id_vars,
        value_vars=time_cols,
        var_name=time_col_name,
        value_name=value_col_name
    )
    
    # 2. 시간대 레이블 인코딩
    time_labels = {name: idx for idx, name in enumerate(sorted(time_cols))}
    df_melt[f'{time_col_name}_label'] = df_melt[time_col_name].map(time_labels)
    
    # 3. 승차/하차를 컬럼으로 피벗 (행 수 절반 감소)
    df_pivot = df_melt.pivot_table(
        index=[col for col in df_melt.columns if col not in [inout_col, value_col_name]],
        columns=inout_col,
        values=value_col_name,
        aggfunc='sum'  # 중복 시 합계 계산
    ).reset_index()
    
    # 4. 컬럼명 정리
    df_pivot.columns = [
        col if col == time_col_name or col == f'{time_col_name}_label' 
        else f'{col}' 
        for col in df_pivot.columns
    ]
    df_final = pd.get_dummies(df_pivot, columns=['요일구분'])
    
    return df_final

inout_22_label = time_label(inout_22, time_cols)
inout_23_label = time_label(inout_23, time_cols)
inout_24_label = time_label(inout_24, time_cols)
inout_24_09_label = time_label(inout_24_09, time_cols)
inout_24_03_label = time_label(inout_24_03, time_cols)
inout_24_06_label = time_label(inout_24_06, time_cols)

In [152]:
inout_22_label.to_csv('2022년 11월 역별 시간대별 승하차인원(label).csv')
inout_23_label.to_csv('2023년 11월 역별 시간대별 승하차인원(label).csv')
inout_24_label.to_csv('2024년 11월 역별 시간대별 승하차인원(label).csv')

In [154]:
inout_24_label

,label,역명,시간대,시간대_label,승차,하차,요일구분_공휴일,요일구분_토요일,요일구분_평일
0,0,온수,06 ~ 07,0,118.000000,69.000000,True,False,False
1,0,온수,07 ~ 08,1,187.750000,124.500000,True,False,False
2,0,온수,08 ~ 09,2,356.250000,195.000000,True,False,False
3,0,온수,09 ~ 10,3,437.750000,237.000000,True,False,False
4,0,온수,10 ~ 11,4,447.250000,272.000000,True,False,False
...,...,...,...,...,...,...,...,...,...
2263,41,장암,19 ~ 20,13,53.523810,147.142857,False,False,True
2264,41,장암,20 ~ 21,14,36.428571,82.809524,False,False,True
2265,41,장암,21 ~ 22,15,23.095238,34.333333,False,False,True
2266,41,장암,22 ~ 23,16,16.142857,42.904762,False,False,True
2267,41,장암,23 ~ 24,17,9.857143,25.238095,False,False,True

In [156]:
def time_cyclic(df, time_cols, time_col_name='시간대', value_col_name='인원수', 
                      inout_col='구분', start_hour=6, end_hour=24, peak_hours=[8, 18]):

    # 1. melt로 시간대별 행 확장
    id_vars = [col for col in df.columns if col not in time_cols]
    df_melt = df.melt(
        id_vars=id_vars,
        value_vars=time_cols,
        var_name=time_col_name,
        value_name=value_col_name
    )
    
    # 2. 시간대에서 시작 시간 추출 (예: '06 ~ 07' → 6)
    df_melt['start_hour'] = df_melt[time_col_name].apply(
        lambda x: int(x.split(' ~ ')[0])
    )
    
    # 3. 주기 인코딩 계산 (사용자 정의 파라미터 적용)
    period = end_hour - start_hour
    shift = peak_hours[0] - (period / 4)  # 예: 8 - 4.5 = 3.5
    angle = 2 * np.pi * (df_melt['start_hour'] - shift) / period
    
    df_melt[f'{time_col_name}_sine'] = np.sin(angle)
    df_melt[f'{time_col_name}_cosine'] = np.cos(angle)
    
    # 4. 불필요한 컬럼 제거
    df_melt = df_melt.drop(columns=['start_hour'])
    
    # 5. 승차/하차를 컬럼으로 피벗 (행 수 절반 감소)
    df_pivot = df_melt.pivot_table(
        index=[col for col in df_melt.columns if col not in [inout_col, value_col_name]],
        columns=inout_col,
        values=value_col_name,
        aggfunc='sum'  # 중복 시 합계 계산
    ).reset_index()
    
    # 6. 컬럼명 정리
    df_pivot.columns = [
        col if col == time_col_name or col in [f'{time_col_name}_sine', f'{time_col_name}_cosine'] 
        else f'{col}' 
        for col in df_pivot.columns
    ]

    df_final = pd.get_dummies(df_pivot, columns=['요일구분'])
    
    return df_final

inout_22_cyclic = time_cyclic(inout_22, time_cols)
inout_23_cyclic = time_cyclic(inout_23, time_cols)
inout_24_cyclic = time_cyclic(inout_24, time_cols)
inout_24_09_cyclic = time_cyclic(inout_24_09, time_cols)
inout_24_03_cyclic = time_cyclic(inout_24_03, time_cols)
inout_24_06_cyclic = time_cyclic(inout_24_06, time_cols)

In [158]:
inout_22_cyclic.to_csv('2022년 11월 역별 시간대별 승하차인원(cyclic).csv')
inout_23_cyclic.to_csv('2023년 11월 역별 시간대별 승하차인원(cyclic).csv')
inout_24_cyclic.to_csv('2024년 11월 역별 시간대별 승하차인원(cyclic).csv')

In [160]:
inout_24_cyclic

,label,역명,시간대,시간대_sine,시간대_cosine,승차,하차,요일구분_공휴일,요일구분_토요일,요일구분_평일
0,0,온수,06 ~ 07,0.766044,6.427876e-01,118.000000,69.000000,True,False,False
1,0,온수,07 ~ 08,0.939693,3.420201e-01,187.750000,124.500000,True,False,False
2,0,온수,08 ~ 09,1.000000,6.123234e-17,356.250000,195.000000,True,False,False
3,0,온수,09 ~ 10,0.939693,-3.420201e-01,437.750000,237.000000,True,False,False
4,0,온수,10 ~ 11,0.766044,-6.427876e-01,447.250000,272.000000,True,False,False
...,...,...,...,...,...,...,...,...,...,...
2263,41,장암,19 ~ 20,-0.766044,6.427876e-01,53.523810,147.142857,False,False,True
2264,41,장암,20 ~ 21,-0.500000,8.660254e-01,36.428571,82.809524,False,False,True
2265,41,장암,21 ~ 22,-0.173648,9.848078e-01,23.095238,34.333333,False,False,True
2266,41,장암,22 ~ 23,0.173648,9.848078e-01,16.142857,42.904762,False,False,True
2267,41,장암,23 ~ 24,0.500000,8.660254e-01,9.857143,25.238095,False,False,True

# Step 4. 지하철 승하차 데이터와 혼잡도 데이터 병합

In [162]:
import numpy as np
import pandas as pd

inout_22_ohe = pd.read_csv('2022년 11월 역별 시간대별 승하차인원(ohe).csv', index_col=0)
inout_23_ohe = pd.read_csv('2023년 11월 역별 시간대별 승하차인원(ohe).csv', index_col=0)
inout_24_ohe = pd.read_csv('2024년 11월 역별 시간대별 승하차인원(ohe).csv', index_col=0)

inout_22_label = pd.read_csv('2022년 11월 역별 시간대별 승하차인원(label).csv', index_col=0)
inout_23_label = pd.read_csv('2023년 11월 역별 시간대별 승하차인원(label).csv', index_col=0)
inout_24_label = pd.read_csv('2024년 11월 역별 시간대별 승하차인원(label).csv', index_col=0)

inout_22_cyclic = pd.read_csv('2022년 11월 역별 시간대별 승하차인원(cyclic).csv', index_col=0)
inout_23_cyclic = pd.read_csv('2023년 11월 역별 시간대별 승하차인원(cyclic).csv', index_col=0)
inout_24_cyclic = pd.read_csv('2024년 11월 역별 시간대별 승하차인원(cyclic).csv', index_col=0)

In [164]:
inout_22_ohe

,label,역명,승차,하차,시간대_06 ~ 07,시간대_07 ~ 08,시간대_08 ~ 09,시간대_09 ~ 10,시간대_10 ~ 11,시간대_11 ~ 12,...,시간대_17 ~ 18,시간대_18 ~ 19,시간대_19 ~ 20,시간대_20 ~ 21,시간대_21 ~ 22,시간대_22 ~ 23,시간대_23 ~ 24,요일구분_공휴일,요일구분_토요일,요일구분_평일
0,0,온수,129.0,64.0,True,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,0,온수,172.0,80.0,False,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,0,온수,297.0,190.0,False,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,0,온수,400.0,164.0,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
4,0,온수,387.0,203.0,False,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2263,41,장암,59.4,131.8,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,True
2264,41,장암,25.4,75.4,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,True
2265,41,장암,25.8,32.0,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
2266,41,장암,13.4,33.4,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
2267,41,장암,6.4,20.4,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True

In [166]:
cong_22 = pd.read_csv('2022년 11월 역별 시간대별 혼잡도(전처리).csv', index_col=0)
cong_23 = pd.read_csv('2023년 11월 역별 시간대별 혼잡도(전처리).csv', index_col=0)
cong_24 = pd.read_csv('2024년 11월 역별 시간대별 혼잡도(전처리).csv', index_col=0)
cong_24_09 = congestion_2024_09_hourly.copy()
cong_24_03 = congestion_2024_03_hourly.copy()
cong_24_06 = congestion_2024_06_hourly.copy()
def onehot_encode_inout(df, inout_col='구분', day_col='요일구분'):

    # 1. 구분, 요일구분 원핫 인코딩
    df_ohe = pd.get_dummies(df, columns=[inout_col, day_col])

    return df_ohe

cong_22_basic = onehot_encode_inout(cong_22)
cong_23_basic = onehot_encode_inout(cong_23)
cong_24_basic = onehot_encode_inout(cong_24)
cong_24_09_basic = onehot_encode_inout(cong_24_09)
cong_24_03_basic = onehot_encode_inout(cong_24_03)
cong_24_06_basic = onehot_encode_inout(cong_24_06)

In [168]:
cong_24_09_basic

,label,역명,06 ~ 07,07 ~ 08,08 ~ 09,09 ~ 10,10 ~ 11,11 ~ 12,12 ~ 13,13 ~ 14,...,19 ~ 20,20 ~ 21,21 ~ 22,22 ~ 23,23 ~ 24,구분_상선,구분_하선,요일구분_일요일,요일구분_토요일,요일구분_평일
0,0,온수,44.434713,80.335532,95.150279,61.298567,29.047771,23.727707,23.452229,20.519108,...,16.044851,14.993232,12.350717,13.998806,10.601115,True,False,False,False,True
1,0,온수,18.872081,20.678742,40.615048,35.587182,37.093949,39.603901,32.121815,34.325239,...,13.616640,14.570064,11.775478,15.167197,9.613854,True,False,False,True,False
2,0,온수,10.315817,11.516720,23.923169,28.310111,32.476115,28.740048,22.060111,25.571258,...,13.748010,14.599920,10.290605,11.743631,5.832006,True,False,True,False,False
3,0,온수,11.973385,20.594575,26.566197,9.073466,13.204087,13.171975,15.234076,17.600318,...,53.029032,31.877654,35.421975,35.716561,32.531847,False,True,False,False,True
4,0,온수,14.815552,13.485271,13.437500,19.444666,18.242436,23.033439,26.731688,24.297373,...,33.815685,25.756369,32.253185,28.493232,25.871815,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,41,장암,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,True,False,False,True,False
248,41,장암,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,True,False,True,False,False
249,41,장암,6.687898,14.727972,8.577495,3.618631,1.786093,1.279193,1.673301,1.397293,...,1.252654,0.658174,0.617038,0.517516,0.199045,False,True,False,False,True
250,41,장암,0.477707,2.607484,2.965764,3.091826,2.766720,2.454883,2.149682,2.507962,...,1.652070,0.656847,1.015127,0.497611,0.358280,False,True,False,True,False
251,41,장암,0.417994,1.273885,1.512739,1.930732,1.990446,2.176221,2.030255,3.138270,...,1.486200,0.835987,0.796178,0.378185,0.039809,False,True,True,False,False

In [170]:
def onehot_congestion(cong):
    # 시간대 컬럼 정의
    hour_columns = ['06 ~ 07', '07 ~ 08', '08 ~ 09', '09 ~ 10', '10 ~ 11',
                    '11 ~ 12', '12 ~ 13', '13 ~ 14', '14 ~ 15', '15 ~ 16', '16 ~ 17',
                    '17 ~ 18', '18 ~ 19', '19 ~ 20', '20 ~ 21', '21 ~ 22', '22 ~ 23', '23 ~ 24']

    # 시간대 외의 나머지 컬럼
    id_vars = [col for col in cong.columns if col not in hour_columns]

    # wide -> long 변환: 혼잡도 값이 value
    df_long = cong.melt(id_vars=id_vars, value_vars=hour_columns, 
                        var_name='시간대', value_name='혼잡도')

    # 시간대 원핫인코딩
    time_onehot = pd.get_dummies(df_long['시간대'], prefix='시간대')
    df_final = pd.concat([df_long, time_onehot], axis=1)

    return df_final

cong_22_ohe = onehot_congestion(cong_22_basic)
cong_23_ohe = onehot_congestion(cong_23_basic)
cong_24_ohe = onehot_congestion(cong_24_basic)
cong_24_09_ohe = onehot_congestion(cong_24_09_basic)
cong_24_03_ohe = onehot_congestion(cong_24_03_basic)
cong_24_06_ohe = onehot_congestion(cong_24_06_basic)

In [172]:
def merge_cong_inout_ohe(cong, inout):
    # 두 데이터프레임의 컬럼 집합
    cong_cols = set(cong.columns)
    inout_cols = set(inout.columns)
    
    # 공통 컬럼 자동 추출
    common_cols = list(cong_cols & inout_cols)
    
    # 병합
    merged = pd.merge(cong, inout, on=common_cols, how='outer', suffixes=('_cong', '_inout'))
    
    # 1. 혼잡도 컬럼을 가장 오른쪽으로 이동
    if '혼잡도' in merged.columns:
        cols = [col for col in merged if col != '혼잡도'] + ['혼잡도']
        merged = merged[cols]
        
    # 2. label 컬럼 기준 오름차순 정렬
    if 'label' in merged.columns:
        merged = merged.sort_values(['label', '시간대'], ascending=True)
    
    return merged.reset_index(drop=True)


total_22_ohe = merge_cong_inout_ohe(cong_22_ohe, inout_22_ohe)
total_23_ohe = merge_cong_inout_ohe(cong_23_ohe, inout_23_ohe)
total_24_ohe = merge_cong_inout_ohe(cong_24_ohe, inout_24_ohe)
total_24_09_ohe = merge_cong_inout_ohe(cong_24_ohe, inout_24_09_ohe)
total_24_03_ohe = merge_cong_inout_ohe(cong_24_ohe, inout_24_03_ohe)
total_24_06_ohe = merge_cong_inout_ohe(cong_24_ohe, inout_24_06_ohe)

In [174]:
from sklearn.preprocessing import LabelEncoder

# 시간대 컬럼 리스트
hour_columns = ['06 ~ 07', '07 ~ 08', '08 ~ 09', '09 ~ 10', '10 ~ 11',
                '11 ~ 12', '12 ~ 13', '13 ~ 14', '14 ~ 15', '15 ~ 16', '16 ~ 17',
                '17 ~ 18', '18 ~ 19', '19 ~ 20', '20 ~ 21', '21 ~ 22', '22 ~ 23', '23 ~ 24']

def label_congestion(cong):
    # 1. wide → long 변환
    hour_columns = [col for col in cong.columns if ' ~ ' in col]
    id_vars = [col for col in cong.columns if col not in hour_columns]
    df_long = cong.melt(id_vars=id_vars, value_vars=hour_columns, 
                        var_name='시간대', value_name='혼잡도')
    
    # 2. 레이블 인코딩
    le = LabelEncoder()
    df_long['시간대_label'] = le.fit_transform(df_long['시간대'])
    
    return df_long

cong_22_label = label_congestion(cong_22_basic)
cong_23_label = label_congestion(cong_23_basic)
cong_24_label = label_congestion(cong_24_basic)
cong_24_09_label = label_congestion(cong_24_09_basic)
cong_24_03_label = label_congestion(cong_24_03_basic)
cong_24_06_label = label_congestion(cong_24_06_basic)

In [176]:
def merge_cong_inout_label(inout, cong):
    # 1. '요일구분_일요일' 컬럼이 있으면 '요일구분_공휴일'로 컬럼명 변경
    if '요일구분_일요일' in inout.columns:
        inout = inout.rename(columns={'요일구분_일요일': '요일구분_공휴일'})
    if '요일구분_일요일' in cong.columns:
        cong = cong.rename(columns={'요일구분_일요일': '요일구분_공휴일'})
    
    # 2. 공통 컬럼 리스트 정의
    common_cols = ['label', '역명', '시간대', '시간대_label', '요일구분_공휴일', '요일구분_토요일', '요일구분_평일']
    
    # 3. 병합
    merged = pd.merge(inout, cong, on=common_cols, how='outer', suffixes=('_inout', '_cong'))
    
    return merged

total_22_label = merge_cong_inout_label(cong_22_label, inout_22_label)
total_23_label = merge_cong_inout_label(cong_23_label, inout_23_label)
total_24_label = merge_cong_inout_label(cong_24_label, inout_24_label)
total_24_09_label = merge_cong_inout_label(cong_24_09_label, inout_24_09_label)
total_24_03_label = merge_cong_inout_label(cong_24_03_label, inout_24_03_label)
total_24_06_label = merge_cong_inout_label(cong_24_06_label, inout_24_06_label)

In [178]:
def merge_inout_cong(inout, cong):
    # 1. '요일구분_일요일' 컬럼이 있으면 '요일구분_공휴일'로 컬럼명 변경
    if '요일구분_일요일' in inout.columns:
        inout = inout.rename(columns={'요일구분_일요일': '요일구분_공휴일'})
    if '요일구분_일요일' in cong.columns:
        cong = cong.rename(columns={'요일구분_일요일': '요일구분_공휴일'})
    
    # 2. 공통 컬럼 리스트 정의
    common_cols = ['label', '역명', '시간대', '요일구분_공휴일', '요일구분_토요일', '요일구분_평일']
    
    # 3. 병합
    merged = pd.merge(inout, cong, on=common_cols, how='outer', suffixes=('_inout', '_cong'))
    
    return merged

total_22_cyclic = merge_inout_cong(cong_22_label, inout_22_cyclic)
total_23_cyclic = merge_inout_cong(cong_23_label, inout_23_cyclic)
total_24_cyclic = merge_inout_cong(cong_24_label, inout_24_cyclic)
total_24_09_cyclic = merge_inout_cong(cong_24_09_label, inout_24_09_cyclic)
total_24_03_cyclic = merge_inout_cong(cong_24_03_label, inout_24_03_cyclic)
total_24_06_cyclic = merge_inout_cong(cong_24_06_label, inout_24_06_cyclic)

In [180]:
total_22_ohe.to_csv('2022년 11월 데이터총합(ohe).csv')
total_23_ohe.to_csv('2023년 11월 데이터총합(ohe).csv')
total_24_ohe.to_csv('2024년 11월 데이터총합(ohe).csv')

total_22_label.to_csv('2022년 11월 데이터총합(label).csv')
total_23_label.to_csv('2023년 11월 데이터총합(label).csv')
total_24_label.to_csv('2024년 11월 데이터총합(label).csv')

total_22_cyclic.to_csv('2022년 11월 데이터총합(cyclic).csv')
total_23_cyclic.to_csv('2023년 11월 데이터총합(cyclic).csv')
total_24_cyclic.to_csv('2024년 11월 데이터총합(cyclic).csv')

# Step 5. 지하철 혼잡도 예측을 위한 모델 학습 수행

In [182]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import Ridge
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

total_22_ohe = pd.read_csv('2022년 11월 데이터총합(ohe).csv', index_col=0)
total_23_ohe = pd.read_csv('2023년 11월 데이터총합(ohe).csv', index_col=0)
total_24_ohe = pd.read_csv('2024년 11월 데이터총합(ohe).csv', index_col=0)

total_22_label = pd.read_csv('2022년 11월 데이터총합(label).csv', index_col=0)
total_23_label = pd.read_csv('2023년 11월 데이터총합(label).csv', index_col=0)
total_24_label = pd.read_csv('2024년 11월 데이터총합(label).csv', index_col=0)

total_22_cyclic = pd.read_csv('2022년 11월 데이터총합(cyclic).csv', index_col=0)
total_23_cyclic = pd.read_csv('2023년 11월 데이터총합(cyclic).csv', index_col=0)
total_24_cyclic = pd.read_csv('2024년 11월 데이터총합(cyclic).csv', index_col=0)

- 1. 원핫인코딩 데이터로 train, validation, test 수행

In [184]:
feature_cols = ['label', '구분_상선', '구분_하선', '요일구분_공휴일', '요일구분_토요일', '요일구분_평일',
                '시간대_06 ~ 07', '시간대_07 ~ 08', '시간대_08 ~ 09', '시간대_09 ~ 10',
                '시간대_10 ~ 11', '시간대_11 ~ 12', '시간대_12 ~ 13', '시간대_13 ~ 14',
                '시간대_14 ~ 15', '시간대_15 ~ 16', '시간대_16 ~ 17', '시간대_17 ~ 18',
                '시간대_18 ~ 19', '시간대_19 ~ 20', '시간대_20 ~ 21', '시간대_21 ~ 22',
                '시간대_22 ~ 23', '시간대_23 ~ 24', '승차', '하차']
label_col = '혼잡도'


# 학습 데이터
X_train = total_22_ohe[feature_cols]
y_train = total_22_ohe[label_col]

# 검증 데이터
X_valid = total_23_ohe[feature_cols]
y_valid = total_23_ohe[label_col]

# 테스트 데이터
X_test = total_24_ohe[feature_cols]
y_test = total_24_ohe[label_col]

In [186]:
X_test

,label,구분_상선,구분_하선,요일구분_공휴일,요일구분_토요일,요일구분_평일,시간대_06 ~ 07,시간대_07 ~ 08,시간대_08 ~ 09,시간대_09 ~ 10,...,시간대_16 ~ 17,시간대_17 ~ 18,시간대_18 ~ 19,시간대_19 ~ 20,시간대_20 ~ 21,시간대_21 ~ 22,시간대_22 ~ 23,시간대_23 ~ 24,승차,하차
0,0,True,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,118.000000,69.000000
1,0,False,True,True,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,118.000000,69.000000
2,0,True,False,False,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,224.000000,86.200000
3,0,False,True,False,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,224.000000,86.200000
4,0,True,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,830.333333,147.809524
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4531,41,False,True,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,6.750000,13.250000
4532,41,True,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,True,9.400000,23.400000
4533,41,False,True,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,True,9.400000,23.400000
4534,41,True,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,True,9.857143,25.238095
4535,41,False,True,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,True,9.857143,25.238095

In [190]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_percentage_error, mean_absolute_error

# 선형 회귀
lr = LinearRegression()

# XGBoost 회귀
xgb = XGBRegressor(objective='reg:squarederror', random_state=42)

# 선형 회귀
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

# XGBoost
xgb.fit(X_train, y_train)
y_pred_xgb = xgb.predict(X_test)

results = {
    'Linear Regression': {
        'MSE': mean_squared_error(y_test, y_pred_lr),
        'R2': r2_score(y_test, y_pred_lr),
        'MAE': mean_absolute_error(y_test, y_pred_lr)
    },
    'XGBRegressor': {
        'MSE': mean_squared_error(y_test, y_pred_xgb),
        'R2': r2_score(y_test, y_pred_xgb),
        'MAE': mean_absolute_error(y_test, y_pred_xgb)
    }
}

pd.set_option('display.float_format', '{:.10f}'.format)

pd.DataFrame(results)

     Linear Regression  XGBRegressor
MSE     271.1944642669 21.2625584333
R2        0.2837534798  0.9438438630
MAE      12.1903591305  3.2730925246

- 2. 레이블인`코딩 데이터로 train, validation, test 수행

In [192]:
# 특징/레이블 컬럼 정의
feature_cols = ['label', '구분_상선', '구분_하선', '요일구분_공휴일', 
                '요일구분_토요일', '요일구분_평일', '시간대_label', '승차', '하차']
label_col = '혼잡도'

# 데이터 분할
X_train = total_22_label[feature_cols]
y_train = total_22_label[label_col]

X_val = total_23_label[feature_cols]
y_val = total_23_label[label_col]

X_test = total_24_label[feature_cols]
y_test = total_24_label[label_col]

In [196]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_percentage_error, mean_absolute_error

# 선형 회귀
lr = LinearRegression()

# XGBoost 회귀
xgb = XGBRegressor(objective='reg:squarederror', random_state=42)

# 선형 회귀
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

# XGBoost
xgb.fit(X_train, y_train)
y_pred_xgb = xgb.predict(X_test)

results = {
    'Linear Regression': {
        'MSE': mean_squared_error(y_test, y_pred_lr),
        'R2': r2_score(y_test, y_pred_lr),
        'MAE': mean_absolute_error(y_test, y_pred_lr)
    },
    'XGBRegressor': {
        'MSE': mean_squared_error(y_test, y_pred_xgb),
        'R2': r2_score(y_test, y_pred_xgb),
        'MAE': mean_absolute_error(y_test, y_pred_xgb)
    }
}

pd.set_option('display.float_format', '{:.10f}'.format)

pd.DataFrame(results)

     Linear Regression  XGBRegressor
MSE     286.5656767368 14.6151125403
R2        0.2431568641  0.9614003054
MAE      12.6769245018  2.6832895330

- 3. 주기인코딩 데이터로 train, validation, test 수행

In [202]:
# 특징/레이블 컬럼 정의
feature_cols = ['label', '구분_상선', '구분_하선', '요일구분_공휴일', '요일구분_토요일', '요일구분_평일', 
                '시간대_label', '승차', '하차', '시간대_sine', '시간대_cosine']
label_col = '혼잡도'

X_train = total_22_cyclic[feature_cols]
y_train = total_22_cyclic[label_col]

X_val = total_23_cyclic[feature_cols]
y_val = total_23_cyclic[label_col]

X_test = total_24_cyclic[feature_cols]
y_test = total_24_cyclic[label_col]

# 선형 회귀
lr = LinearRegression()

# XGBoost 회귀
xgb = XGBRegressor(objective='reg:squarederror', random_state=42)

# 선형 회귀
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

# XGBoost
xgb.fit(X_train, y_train)
y_pred_xgb = xgb.predict(X_test)

results = {
    'Linear Regression': {
        'MSE': mean_squared_error(y_test, y_pred_lr),
        'R2': r2_score(y_test, y_pred_lr),
        'MAE': mean_absolute_error(y_test, y_pred_lr)
    },
    'XGBRegressor': {
        'MSE': mean_squared_error(y_test, y_pred_xgb),
        'R2': r2_score(y_test, y_pred_xgb),
        'MAE': mean_absolute_error(y_test, y_pred_xgb)
    }
}
pd.set_option('display.float_format', '{:.10f}'.format)

pd.DataFrame(results)

     Linear Regression  XGBRegressor
MSE     279.1123179708 15.0154213633
R2        0.2628417876  0.9603430574
MAE      12.3811228719  2.7278851464

- 4. 원핫인코딩 데이터셋으로 성능 향상 시도

In [204]:
feature_cols = ['label', '구분_상선', '구분_하선', '요일구분_공휴일', '요일구분_토요일', '요일구분_평일',
                '시간대_06 ~ 07', '시간대_07 ~ 08', '시간대_08 ~ 09', '시간대_09 ~ 10',
                '시간대_10 ~ 11', '시간대_11 ~ 12', '시간대_12 ~ 13', '시간대_13 ~ 14',
                '시간대_14 ~ 15', '시간대_15 ~ 16', '시간대_16 ~ 17', '시간대_17 ~ 18',
                '시간대_18 ~ 19', '시간대_19 ~ 20', '시간대_20 ~ 21', '시간대_21 ~ 22',
                '시간대_22 ~ 23', '시간대_23 ~ 24', '승차', '하차']
label_col = '혼잡도'

# 데이터 분할
X_train = total_22_ohe[feature_cols]
y_train = total_22_ohe[label_col]

X_val = total_23_ohe[feature_cols]
y_val = total_23_ohe[label_col]

X_test = total_24_ohe[feature_cols]
y_test = total_24_ohe[label_col]

# 3. 선형 회귀 최적화
# 다항식 변환 (2차)
poly = PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

# 정규화
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_poly)
X_test_scaled = scaler.transform(X_test_poly)

# 릿지 회귀
ridge = Ridge(alpha=0.1)
ridge.fit(X_train_scaled, y_train)
y_pred_ridge = ridge.predict(X_test_scaled)

# 4. XGBoost 최적화
xgb = XGBRegressor(
    n_estimators=1500,
    learning_rate=0.05,
    max_depth=7,
    subsample=0.8,
    colsample_bytree=0.7,
    gamma=0.2,
    reg_alpha=0.5,
    reg_lambda=1.0,
    random_state=42,
    early_stopping_rounds=100,  # 생성자로 이동
    eval_metric='rmse'          # 필수 추가
)

xgb.fit(
    X_train, y_train,
    eval_set=[(X_val, y_val)],
    verbose=False
)
y_pred_xgb = xgb.predict(X_test)

# 5. 성능 평가
results = {
    'Ridge': {
        'MSE': mean_squared_error(y_test, y_pred_ridge),
        'R2': r2_score(y_test, y_pred_ridge), 
        'MAE' : mean_absolute_error(y_test, y_pred_ridge)
    },
    'XGBoost': {
        'MSE': mean_squared_error(y_test, y_pred_xgb),
        'R2': r2_score(y_test, y_pred_xgb), 
        'MAE' : mean_absolute_error(y_test, y_pred_xgb)
    }
}

pd.DataFrame(results)

             Ridge       XGBoost
MSE 237.8509502053 11.7793942670
R2    0.3718163980  0.9688896668
MAE  11.6448240298  2.4215602679

- 5. 레이블인코딩 데이터셋으로 성능 향상 시도

In [208]:
# 특징/레이블 컬럼 정의
feature_cols = ['label', '구분_상선', '구분_하선', '요일구분_공휴일', 
                '요일구분_토요일', '요일구분_평일', '시간대_label', '승차', '하차']
label_col = '혼잡도'

# 데이터 분할
X_train = total_22_label[feature_cols]
y_train = total_22_label[label_col]

X_val = total_23_label[feature_cols]
y_val = total_23_label[label_col]

X_test = total_24_label[feature_cols]
y_test = total_24_label[label_col]

# 정규화 (Ridge용)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

In [210]:
# 하이퍼파라미터 그리드
ridge_params = {'alpha': [0.001, 0.01, 0.1, 1, 10, 100]}

# 그리드서치 수행
ridge_grid = GridSearchCV(
    Ridge(),
    param_grid=ridge_params,
    scoring='neg_mean_squared_error',
    cv=5,
    n_jobs=-1
)
ridge_grid.fit(X_train_scaled, y_train)

# 최적 모델 추출
best_ridge = ridge_grid.best_estimator_

# 하이퍼파라미터 그리드
xgb_params = {
    'max_depth': [5, 7],
    'learning_rate': [0.01, 0.05],
    'subsample': [0.6, 0.8],
    'colsample_bytree': [0.7, 0.8]
}

# 기본 모델
xgb_base = XGBRegressor(
    n_estimators=1000,
    early_stopping_rounds=100,
    eval_metric='rmse',
    random_state=42
)

# 랜덤서치 수행
xgb_search = GridSearchCV(
    xgb_base,
    param_grid=xgb_params,
    scoring='neg_mean_squared_error',
    cv=3,
    n_jobs=-1
)
xgb_search.fit(
    X_train, y_train,
    eval_set=[(X_val, y_val)],
    verbose=False
)

# 최적 모델 추출
best_xgb = xgb_search.best_estimator_

# Ridge 평가
y_pred_ridge = best_ridge.predict(X_test_scaled)

# XGBoost 평가
y_pred_xgb = best_xgb.predict(X_test)

# 결과 비교
results = {
    'Ridge': {
        'MSE': mean_squared_error(y_test, y_pred_ridge),
        'R2': r2_score(y_test, y_pred_ridge), 
        'MAE' : mean_absolute_error(y_test, y_pred_ridge)
    },
    'XGBoost': {
        'MSE': mean_squared_error(y_test, y_pred_xgb),
        'R2': r2_score(y_test, y_pred_xgb), 
        'MAE' : mean_absolute_error(y_test, y_pred_xgb)
    }
}

pd.DataFrame(results)

             Ridge       XGBoost
MSE 286.5899109337 15.5515463421
R2    0.2430928597  0.9589271080
MAE  12.6847576367  2.6805583749

- 6. 주기인코딩 데이터셋으로 성능 향상 시도

In [212]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_percentage_error, mean_absolute_error
feature_cols = ['label', '구분_상선', '구분_하선', '요일구분_공휴일', '요일구분_토요일', '요일구분_평일', 
                '시간대_label', '승차', '하차', '시간대_sine', '시간대_cosine']
label_col = '혼잡도'

X_train = total_22_cyclic[feature_cols]
y_train = total_22_cyclic[label_col]

X_val = total_23_cyclic[feature_cols]
y_val = total_23_cyclic[label_col]

X_test = total_24_cyclic[feature_cols]
y_test = total_24_cyclic[label_col]

In [218]:
# 2. Ridge 회귀 최적화
# ------------------------------------------------------------
# 파이프라인 구성
ridge_pipe = Pipeline([
    ('scaler', StandardScaler()),
    ('ridge', Ridge())
])

# 하이퍼파라미터 그리드
ridge_params = {
    'ridge__alpha': [0.001, 0.01, 0.1, 1, 10, 100],
    'ridge__solver': ['svd', 'cholesky', 'lsqr']
}

# 그리드서치 수행
ridge_grid = GridSearchCV(
    ridge_pipe,
    param_grid=ridge_params,
    scoring='neg_mean_squared_error',
    cv=5,
    n_jobs=-1
)
ridge_grid.fit(X_train, y_train)

# 3. XGBoost 최적화
# ------------------------------------------------------------
# 3. XGBoost 최적화 (xgboost.cv 활용)
# ------------------------------------------------------------
import xgboost as xgb
from itertools import product
import numpy as np

# 데이터 DMatrix 변환
dtrain = xgb.DMatrix(X_train, label=y_train)
dval = xgb.DMatrix(X_val, label=y_val)  # 검증 세트

# 하이퍼파라미터 그리드
param_grid = {
    'max_depth': [5, 7],
    'learning_rate': [0.01, 0.05, 0.1],
    'subsample': [0.6, 0.8],
    'colsample_bytree': [0.7, 0.8],
    'gamma': [0, 0.1, 0.2]
}

# 최적 결과 추적용
best_score = np.inf
best_params = None
best_n_estimators = 0

# 그리드 서치 수동 구현
for params in product(*param_grid.values()):
    current_params = dict(zip(param_grid.keys(), params))
    
    # CV 수행
    cv_results = xgb.cv(
        params={**current_params, 'objective': 'reg:squarederror'},
        dtrain=dtrain,
        nfold=3,
        num_boost_round=2000,
        early_stopping_rounds=200,
        metrics='rmse',
        seed=42,
        verbose_eval=False
    )
    
    # 최적 라운드 찾기
    best_round = cv_results.shape[0]
    best_rmse = cv_results['test-rmse-mean'].min()
    
    # 검증 세트로 추가 평가
    model = xgb.train(
        {**current_params, 'objective': 'reg:squarederror'},
        dtrain,
        num_boost_round=best_round,
        evals=[(dval, 'eval')],
        verbose_eval=False
    )
    
    # 성능 비교
    if best_rmse < best_score:
        best_score = best_rmse
        best_params = current_params
        best_n_estimators = best_round

# 최종 모델 훈련
final_xgb = xgb.XGBRegressor(
    **best_params,
    n_estimators=best_n_estimators,
    random_state=42
).fit(X_train, y_train)

In [222]:
y_pred_ridge = ridge_grid.best_estimator_.predict(X_test)
y_pred_xgb = final_xgb.predict(X_test)

results = {
    'Ridge Regression': {
        'MSE': mean_squared_error(y_test, y_pred_ridge),
        'R2': r2_score(y_test, y_pred_ridge),
        'MAE': mean_absolute_error(y_test, y_pred_ridge)
    },
    'XGBRegressor': {
        'MSE': mean_squared_error(y_test, y_pred_xgb),
        'R2': r2_score(y_test, y_pred_xgb),
        'MAE': mean_absolute_error(y_test, y_pred_xgb)
    }
}

pd.set_option('display.float_format', '{:.10f}'.format)
# 딕셔너리를 데이터프레임으로 변환
pd.DataFrame(results)

     Ridge Regression  XGBRegressor
MSE    279.1565943224  7.4526953590
R2       0.2627248502  0.9803168286
MAE     12.3840326190  1.9653865346

- 7. 주기인코딩 데이터셋으로 다른 시기 혼잡도 데이터셋 추가 검정

In [224]:
total_24_03_cyclic = total_24_03_cyclic.dropna()
total_24_03_cyclic = total_24_03_cyclic.reset_index(drop=True)

total_24_06_cyclic = total_24_06_cyclic.dropna()
total_24_06_cyclic = total_24_06_cyclic.reset_index(drop=True)

X_test_1 = total_24_03_cyclic[feature_cols]
y_test_1 = total_24_03_cyclic[label_col]

X_test_2 = total_24_06_cyclic[feature_cols]
y_test_2 = total_24_06_cyclic[label_col]

X_test_3 = total_24_09_cyclic[feature_cols]
y_test_3 = total_24_09_cyclic[label_col]

In [226]:
y_pred_xgb_1 = final_xgb.predict(X_test_1)
y_pred_xgb_2 = final_xgb.predict(X_test_2)
y_pred_xgb_3 = final_xgb.predict(X_test_3)

In [228]:
y_pred_xgb_1 = final_xgb.predict(X_test_1)
y_pred_xgb_2 = final_xgb.predict(X_test_2)
y_pred_xgb_3 = final_xgb.predict(X_test_3)

results_1 = {
    'XGBRegressor': {
        'MSE': mean_squared_error(y_test_1, y_pred_xgb_1),
        'R2': r2_score(y_test_1, y_pred_xgb_1),
        'MAE': mean_absolute_error(y_test_1, y_pred_xgb_1)
    }
}

results_2 = {
    'XGBRegressor': {
        'MSE': mean_squared_error(y_test_2, y_pred_xgb_2),
        'R2': r2_score(y_test_2, y_pred_xgb_2),
        'MAE': mean_absolute_error(y_test_2, y_pred_xgb_2)
    }
}

results_3 = {
    'XGBRegressor': {
        'MSE': mean_squared_error(y_test_3, y_pred_xgb_3),
        'R2': r2_score(y_test_3, y_pred_xgb_3),
        'MAE': mean_absolute_error(y_test_3, y_pred_xgb_3)
    }
}
pd.set_option('display.float_format', '{:.10f}'.format)
# 딕셔너리를 데이터프레임으로 변환

In [230]:
df1 = pd.DataFrame(results_1).T
df2 = pd.DataFrame(results_2).T
df3 = pd.DataFrame(results_3).T

# 데이터프레임 합치기 (index에 구분자 추가)
df1.index = ['2024년 3월']
df2.index = ['2024년 6월']
df3.index = ['2024년 9월']

# 세 데이터프레임 합치기
df_combined = pd.concat([df1, df2, df3])

df_combined.T

         2024년 3월      2024년 6월      2024년 9월
MSE 10.8983504287 13.9196966512 11.9066123602
R2   0.9725923301  0.9602323310  0.9698412840
MAE  2.3413370109  2.6498631671  2.2947694578